
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul  9 2026 10:38:44 IST (Jul  9 2026 05:08:44 UTC)

// Verification Directory fv/uart_top_pad 

module baud_gen_CLK_FREQ50000000_BAUD_RATE9600(clk, rst_n,
     baud_tick_16x);
  input clk, rst_n;
  output baud_tick_16x;
  wire clk, rst_n;
  wire baud_tick_16x;
  wire [8:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_19, n_22, n_23, n_24, n_27;
  dfcrq1 \count_reg[8] (.CDN (rst_n), .CP (clk), .D (n_24), .Q
       (count[8]));
  nr02d1 g322__2398(.A1 (n_10), .A2 (n_0), .ZN (n_24));
  dfcrq1 \count_reg[7] (.CDN (rst_n), .CP (clk), .D (n_23), .Q
       (count[7]));
  ah01d1 g325__5107(.A (n_19), .B (count[7]), .CO (n_22), .S (n_23));
  dfcrq1 \count_reg[6] (.CDN (rst_n), .CP (clk), .D (n_27), .Q
       (count[6]));
  dfcrq1 \count_reg[5] (.CDN (rst_n), .CP (clk), .D (n_16), .Q
       (count[5]));
  an02d1 g331__5526(.A1 (n_17), .A2 (count[6]), .Z (n_19));
  ah01d1 g332__6783(.A (n_14), .B (count[5]), .CO (n_17), .S (n_16));
  dfcrq1 \count_reg[4] (.CDN (rst_n), .CP (clk), .D (n_15), .Q
       (count[4]));
  ah01d1 g334__3680(.A (n_12), .B (count[4]), .CO (n_14), .S (n_15));
  dfcrq1 \count_reg[3] (.CDN (rst_n), .CP (clk), .D (n_13), .Q
       (count[3]));
  dfcrq1 \count_reg[2] (.CDN (rst_n), .CP (clk), .D (n_1), .Q
       (count[2]));
  dfcrq2 \count_reg[0] (.CDN (rst_n), .CP (clk), .D (n_11), .Q
       (count[0]));
  ah01d1 g338__1617(.A (n_8), .B (count[3]), .CO (n_12), .S (n_13));
  dfcrq4 baud_tick_16x_reg(.CDN (rst_n), .CP (clk), .D (n_10), .Q
       (baud_tick_16x));
  nr02d1 g340__2802(.A1 (count[0]), .A2 (n_10), .ZN (n_11));
  an04d4 g342__1705(.A1 (n_7), .A2 (n_3), .A3 (n_4), .A4 (count[2]), .Z
       (n_10));
  ah01d1 g344__5122(.A (n_2), .B (count[2]), .CO (n_8), .S (n_9));
  dfcrq1 \count_reg[1] (.CDN (rst_n), .CP (clk), .D (n_6), .Q
       (count[1]));
  nr02d1 g346__8246(.A1 (count[4]), .A2 (n_5), .ZN (n_7));
  nr02d1 g347__7098(.A1 (n_3), .A2 (n_2), .ZN (n_6));
  nd13d1 g348__6131(.A1 (count[5]), .A2 (count[8]), .A3 (count[6]), .ZN
       (n_5));
  nr02d1 g349__1881(.A1 (count[3]), .A2 (count[7]), .ZN (n_4));
  nr02d2 g350__5115(.A1 (count[0]), .A2 (count[1]), .ZN (n_3));
  an02d1 g351__7482(.A1 (count[0]), .A2 (count[1]), .Z (n_2));
  an12d1 g2__4733(.A1 (n_10), .A2 (n_9), .Z (n_1));
  xn02d1 g353__6161(.A1 (count[8]), .A2 (n_22), .ZN (n_0));
  aoim211d2 g2(.A (n_10), .B (n_19), .C1 (count[6]), .C2 (n_17), .ZN
       (n_27));
endmodule

module uart_rx(clk, rst_n, baud_tick_16x, rx_serial, rx_data, rx_done,
     parity_error, framing_error);
  input clk, rst_n, baud_tick_16x, rx_serial;
  output [7:0] rx_data;
  output rx_done, parity_error, framing_error;
  wire clk, rst_n, baud_tick_16x, rx_serial;
  wire [7:0] rx_data;
  wire rx_done, parity_error, framing_error;
  wire [2:0] state;
  wire [7:0] data_reg;
  wire [3:0] tick_cnt;
  wire [2:0] bit_idx;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_104, n_105, n_106, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_122, n_123, n_124, parity_calc, rx_sync_ff1,
       rx_sync_ff2;
  inv0d1 g3028(.I (state[1]), .ZN (n_10));
  dfcrq1 parity_error_reg(.CDN (rst_n), .CP (clk), .D (n_115), .Q
       (n_117));
  nr02d1 g3103__9315(.A1 (n_105), .A2 (n_102), .ZN (n_115));
  xr03d1 g3106__9945(.A1 (n_112), .A2 (data_reg[2]), .A3 (data_reg[3]),
       .Z (n_114));
  dfcrq1 framing_error_reg(.CDN (rst_n), .CP (clk), .D (n_113), .Q
       (n_116));
  dfcrq1 rx_done_reg(.CDN (rst_n), .CP (clk), .D (n_111), .Q (n_118));
  nr02d1 g3109__2883(.A1 (rx_sync_ff2), .A2 (n_105), .ZN (n_113));
  xr03d1 g3110__2346(.A1 (n_101), .A2 (parity_calc), .A3 (data_reg[5]),
       .Z (n_112));
  inv0d2 g3112(.I (n_111), .ZN (n_105));
  an03d2 g3113__1666(.A1 (n_109), .A2 (n_6), .A3 (state[2]), .Z
       (n_111));
  inv0d1 g3114(.I (n_109), .ZN (n_110));
  nr02d2 g3115__7410(.A1 (n_122), .A2 (tick_cnt[3]), .ZN (n_109));
  xr03d1 g3116__6417(.A1 (n_106), .A2 (data_reg[7]), .A3 (data_reg[4]),
       .Z (n_108));
  nd12d2 g3117__5477(.A1 (n_123), .A2 (baud_tick_16x), .ZN (n_122));
  dfprb4 rx_sync_ff2_reg(.SDN (rst_n), .CP (clk), .D (rx_sync_ff1), .Q
       (rx_sync_ff2), .QN (n_3));
  nd03d4 g3119__2398(.A1 (tick_cnt[2]), .A2 (tick_cnt[0]), .A3
       (tick_cnt[1]), .ZN (n_123));
  dfprb1 rx_sync_ff1_reg(.SDN (rst_n), .CP (clk), .D (n_104), .Q
       (rx_sync_ff1), .QN (UNCONNECTED));
  inv0d2 g3122(.I (n_6), .ZN (n_124));
  an12d2 g3123__5107(.A1 (state[0]), .A2 (n_10), .Z (n_6));
  buffd1 drc_bufs(.I (rx_serial), .Z (n_104));
  bufbd4 drc(.I (n_105), .Z (n_2));
  buffd4 drc_bufs3131(.I (n_118), .Z (rx_done));
  buffd4 drc_bufs3132(.I (n_117), .Z (parity_error));
  buffd4 drc_bufs3133(.I (n_116), .Z (framing_error));
  xn02d1 g2__6260(.A1 (n_114), .A2 (n_108), .ZN (n_102));
  xn02d1 g3137__4319(.A1 (data_reg[1]), .A2 (data_reg[6]), .ZN (n_101));
  dfcrq2 \data_reg_reg[1] (.CDN (rst_n), .CP (clk), .D (n_77), .Q
       (data_reg[1]));
  dfcrq2 \data_reg_reg[2] (.CDN (rst_n), .CP (clk), .D (n_76), .Q
       (data_reg[2]));
  dfcrq2 \data_reg_reg[3] (.CDN (rst_n), .CP (clk), .D (n_75), .Q
       (data_reg[3]));
  dfcrq2 \data_reg_reg[4] (.CDN (rst_n), .CP (clk), .D (n_81), .Q
       (data_reg[4]));
  dfcrq2 \data_reg_reg[5] (.CDN (rst_n), .CP (clk), .D (n_72), .Q
       (data_reg[5]));
  dfcrq2 \data_reg_reg[6] (.CDN (rst_n), .CP (clk), .D (n_74), .Q
       (data_reg[6]));
  dfcrq2 \data_reg_reg[7] (.CDN (rst_n), .CP (clk), .D (n_73), .Q
       (data_reg[7]));
  dfcrq1 parity_calc_reg(.CDN (rst_n), .CP (clk), .D (n_47), .Q
       (parity_calc));
  dfcrq1 \rx_data_reg[0] (.CDN (rst_n), .CP (clk), .D (n_25), .Q
       (n_93));
  dfcrq1 \rx_data_reg[1] (.CDN (rst_n), .CP (clk), .D (n_24), .Q
       (n_94));
  dfcrq1 \rx_data_reg[2] (.CDN (rst_n), .CP (clk), .D (n_30), .Q
       (n_95));
  dfcrq1 \rx_data_reg[3] (.CDN (rst_n), .CP (clk), .D (n_31), .Q
       (n_96));
  dfcrq1 \rx_data_reg[4] (.CDN (rst_n), .CP (clk), .D (n_29), .Q
       (n_97));
  dfcrq1 \rx_data_reg[5] (.CDN (rst_n), .CP (clk), .D (n_28), .Q
       (n_98));
  dfcrq1 \rx_data_reg[6] (.CDN (rst_n), .CP (clk), .D (n_26), .Q
       (n_99));
  dfcrq1 \rx_data_reg[7] (.CDN (rst_n), .CP (clk), .D (n_27), .Q
       (n_100));
  sdcrq4 \state_reg[0] (.CDN (rst_n), .CP (clk), .D (state[0]), .SD
       (n_16), .SC (n_83), .Q (state[0]));
  dfcrq4 \state_reg[1] (.CDN (rst_n), .CP (clk), .D (n_87), .Q
       (state[1]));
  dfcrq4 \tick_cnt_reg[0] (.CDN (rst_n), .CP (clk), .D (n_56), .Q
       (tick_cnt[0]));
  dfcrq2 \tick_cnt_reg[2] (.CDN (rst_n), .CP (clk), .D (n_71), .Q
       (tick_cnt[2]));
  dfcrq4 \tick_cnt_reg[3] (.CDN (rst_n), .CP (clk), .D (n_63), .Q
       (tick_cnt[3]));
  nd02d0 g3423__8428(.A1 (n_86), .A2 (n_85), .ZN (n_87));
  or04d1 g3425__5526(.A1 (n_82), .A2 (n_0), .A3 (n_9), .A4 (state[1]),
       .Z (n_86));
  oaim21d1 g3427__6783(.A (state[1]), .B1 (n_83), .B2 (n_17), .ZN
       (n_85));
  oaim21d1 g3428__3680(.A (n_36), .B1 (n_82), .B2 (state[2]), .ZN
       (n_84));
  inv0d1 g3434(.I (n_83), .ZN (n_82));
  aor211d2 g3440__1617(.A (n_79), .B (n_37), .C1 (n_20), .C2 (n_17), .Z
       (n_83));
  oaim21d1 g3441__2802(.A (n_64), .B1 (n_60), .B2 (n_18), .ZN (n_81));
  aor22d1 g3442__1705(.A1 (n_62), .A2 (tick_cnt[1]), .B1 (n_52), .B2
       (tick_cnt[0]), .Z (n_80));
  aor211d1 g3443__5122(.A (n_57), .B (n_33), .C1 (n_124), .C2
       (state[2]), .Z (n_79));
  aor22d1 g3444__8246(.A1 (n_61), .A2 (n_18), .B1 (n_59), .B2
       (data_reg[0]), .Z (n_78));
  oaim21d1 g3445__7098(.A (n_66), .B1 (n_61), .B2 (n_15), .ZN (n_77));
  oaim21d1 g3447__6131(.A (n_65), .B1 (n_61), .B2 (n_22), .ZN (n_76));
  oaim21d1 g3448__1881(.A (n_70), .B1 (n_61), .B2 (n_14), .ZN (n_75));
  oaim21d1 g3449__5115(.A (n_69), .B1 (n_60), .B2 (n_22), .ZN (n_74));
  oaim21d1 g3450__7482(.A (n_67), .B1 (n_60), .B2 (n_14), .ZN (n_73));
  oaim21d1 g3451__4733(.A (n_68), .B1 (n_60), .B2 (n_15), .ZN (n_72));
  oaim21d1 g3452__6161(.A (n_51), .B1 (n_62), .B2 (tick_cnt[2]), .ZN
       (n_71));
  oaim21d1 g3453__9315(.A (data_reg[3]), .B1 (n_49), .B2 (n_14), .ZN
       (n_70));
  oaim21d1 g3454__9945(.A (data_reg[6]), .B1 (n_50), .B2 (n_22), .ZN
       (n_69));
  oaim21d1 g3459__2883(.A (data_reg[5]), .B1 (n_50), .B2 (n_15), .ZN
       (n_68));
  oaim21d1 g3460__2346(.A (data_reg[7]), .B1 (n_50), .B2 (n_14), .ZN
       (n_67));
  oaim21d1 g3461__1666(.A (data_reg[1]), .B1 (n_49), .B2 (n_15), .ZN
       (n_66));
  oaim21d1 g3462__7410(.A (data_reg[2]), .B1 (n_49), .B2 (n_22), .ZN
       (n_65));
  oaim21d1 g3463__6417(.A (data_reg[4]), .B1 (n_50), .B2 (n_18), .ZN
       (n_64));
  oai222d2 g3464__5477(.A1 (n_45), .A2 (n_34), .B1 (n_43), .B2 (n_9),
       .C1 (n_39), .C2 (n_110), .ZN (n_63));
  nd02d0 g3465__2398(.A1 (n_49), .A2 (n_18), .ZN (n_59));
  nd12d1 g3466__5107(.A1 (n_53), .A2 (n_43), .ZN (n_62));
  an02d2 g3468__6260(.A1 (n_49), .A2 (rx_sync_ff2), .Z (n_61));
  an02d2 g3469__4319(.A1 (n_50), .A2 (rx_sync_ff2), .Z (n_60));
  aor21d1 g3470__8428(.A (n_48), .B1 (n_40), .B2 (bit_idx[1]), .Z
       (n_58));
  an03d1 g3471__5526(.A1 (n_46), .A2 (n_14), .A3 (bit_idx[2]), .Z
       (n_57));
  aor21d1 g3472__6783(.A (n_53), .B1 (n_42), .B2 (tick_cnt[0]), .Z
       (n_56));
  aor22d1 g3473__3680(.A1 (n_46), .A2 (n_35), .B1 (n_40), .B2
       (bit_idx[2]), .Z (n_55));
  mx02d1 g3474__1617(.I0 (n_46), .I1 (n_40), .S (bit_idx[0]), .Z
       (n_54));
  nr02d1 g3475__2802(.A1 (tick_cnt[1]), .A2 (n_45), .ZN (n_52));
  or02d0 g3476__1705(.A1 (n_45), .A2 (n_38), .Z (n_51));
  nr02d2 g3477__5122(.A1 (n_45), .A2 (tick_cnt[0]), .ZN (n_53));
  ora21d1 g3478__8246(.A (n_46), .B1 (n_22), .B2 (n_15), .Z (n_48));
  mx02d1 g3479__7098(.I0 (parity_calc), .I1 (rx_sync_ff2), .S (n_44),
       .Z (n_47));
  an03d4 g3480__6131(.A1 (n_41), .A2 (n_9), .A3 (bit_idx[2]), .Z
       (n_50));
  an03d4 g3481__1881(.A1 (n_41), .A2 (n_9), .A3 (n_11), .Z (n_49));
  an02d2 g3482__5115(.A1 (n_41), .A2 (tick_cnt[3]), .Z (n_46));
  ora31d2 g3483__7482(.A (n_1), .B1 (n_124), .B2 (n_8), .B3 (n_13), .Z
       (n_45));
  an02d1 g3484__4733(.A1 (n_32), .A2 (state[1]), .Z (n_44));
  inv0d1 g3493(.I (n_43), .ZN (n_42));
  aoim22d2 g3494__6161(.A1 (n_8), .A2 (state[1]), .B1 (rx_sync_ff2),
       .B2 (n_0), .Z (n_39));
  aoi22d1 g3495__9315(.A1 (n_21), .A2 (tick_cnt[0]), .B1 (n_5), .B2
       (tick_cnt[2]), .ZN (n_38));
  an04d1 g3497__9945(.A1 (n_7), .A2 (rx_sync_ff2), .A3 (n_10), .A4
       (state[0]), .Z (n_37));
  nd13d1 g3498__2883(.A1 (n_0), .A2 (n_20), .A3 (state[1]), .ZN (n_36));
  mx02d1 g3499__2346(.I0 (bit_idx[2]), .I1 (n_11), .S (n_14), .Z
       (n_35));
  aoim22d2 g3500__1666(.A1 (n_23), .A2 (n_124), .B1 (baud_tick_16x),
       .B2 (n_8), .Z (n_43));
  an03d2 g3501__7410(.A1 (n_7), .A2 (n_16), .A3 (state[1]), .Z (n_41));
  aor21d2 g3502__6417(.A (n_17), .B1 (n_19), .B2 (state[1]), .Z (n_40));
  mx02d1 g3503__5477(.I0 (tick_cnt[3]), .I1 (n_9), .S (n_123), .Z
       (n_34));
  an03d1 g3504__2398(.A1 (n_6), .A2 (n_3), .A3 (n_8), .Z (n_33));
  nr02d1 g3505__5107(.A1 (n_0), .A2 (n_110), .ZN (n_32));
  mx02d1 g3506__6260(.I0 (data_reg[3]), .I1 (n_96), .S (n_2), .Z
       (n_31));
  mx02d1 g3507__4319(.I0 (data_reg[2]), .I1 (n_95), .S (n_2), .Z
       (n_30));
  mx02d1 g3508__8428(.I0 (data_reg[4]), .I1 (n_97), .S (n_2), .Z
       (n_29));
  mx02d1 g3509__5526(.I0 (data_reg[5]), .I1 (n_98), .S (n_2), .Z
       (n_28));
  mx02d1 g3510__6783(.I0 (data_reg[7]), .I1 (n_100), .S (n_2), .Z
       (n_27));
  mx02d1 g3511__3680(.I0 (data_reg[6]), .I1 (n_99), .S (n_2), .Z
       (n_26));
  mx02d1 g3512__1617(.I0 (data_reg[0]), .I1 (n_93), .S (n_2), .Z
       (n_25));
  mx02d1 g3513__2802(.I0 (data_reg[1]), .I1 (n_94), .S (n_2), .Z
       (n_24));
  nr02d1 g3515__1705(.A1 (tick_cnt[2]), .A2 (n_5), .ZN (n_21));
  or02d1 g3516__5122(.A1 (state[2]), .A2 (n_13), .Z (n_23));
  an02d4 g3518__8246(.A1 (n_12), .A2 (bit_idx[1]), .Z (n_22));
  inv0d1 g3519(.I (n_19), .ZN (n_20));
  inv0d1 g3520(.I (n_17), .ZN (n_16));
  or02d1 g3521__7098(.A1 (n_122), .A2 (n_9), .Z (n_19));
  an02d2 g3522__6131(.A1 (n_4), .A2 (n_12), .Z (n_18));
  or02d2 g3523__1881(.A1 (state[2]), .A2 (state[0]), .Z (n_17));
  an02d4 g3524__5115(.A1 (n_4), .A2 (bit_idx[0]), .Z (n_15));
  an02d4 g3525__7482(.A1 (bit_idx[1]), .A2 (bit_idx[0]), .Z (n_14));
  inv0d1 g3526(.I (baud_tick_16x), .ZN (n_13));
  invbd2 g3531(.I (tick_cnt[3]), .ZN (n_9));
  inv0d1 g3533(.I (n_122), .ZN (n_7));
  buffd4 drc_bufs3590(.I (n_95), .Z (rx_data[2]));
  buffd4 drc_bufs3594(.I (n_99), .Z (rx_data[6]));
  buffd4 drc_bufs3598(.I (n_94), .Z (rx_data[1]));
  buffd4 drc_bufs3602(.I (n_98), .Z (rx_data[5]));
  buffd4 drc_bufs3606(.I (n_93), .Z (rx_data[0]));
  buffd4 drc_bufs3610(.I (n_100), .Z (rx_data[7]));
  buffd4 drc_bufs3614(.I (n_97), .Z (rx_data[4]));
  buffd4 drc_bufs3618(.I (n_96), .Z (rx_data[3]));
  nd13d1 g3138__4733(.A1 (n_23), .A2 (n_123), .A3 (n_124), .ZN (n_1));
  nd12d2 g3680__6161(.A1 (state[2]), .A2 (state[0]), .ZN (n_0));
  dfcrb1 \data_reg_reg[0] (.CDN (rst_n), .CP (clk), .D (n_78), .Q
       (data_reg[0]), .QN (n_106));
  dfcrb2 \bit_idx_reg[0] (.CDN (rst_n), .CP (clk), .D (n_54), .Q
       (bit_idx[0]), .QN (n_12));
  dfcrb2 \bit_idx_reg[2] (.CDN (rst_n), .CP (clk), .D (n_55), .Q
       (bit_idx[2]), .QN (n_11));
  dfcrb4 \state_reg[2] (.CDN (rst_n), .CP (clk), .D (n_84), .Q
       (state[2]), .QN (n_8));
  dfcrb2 \tick_cnt_reg[1] (.CDN (rst_n), .CP (clk), .D (n_80), .Q
       (tick_cnt[1]), .QN (n_5));
  dfcrb2 \bit_idx_reg[1] (.CDN (rst_n), .CP (clk), .D (n_58), .Q
       (bit_idx[1]), .QN (n_4));
endmodule

module uart_tx(clk, rst_n, baud_tick_16x, tx_start, tx_data, tx_serial,
     tx_busy);
  input clk, rst_n, baud_tick_16x, tx_start;
  input [7:0] tx_data;
  output tx_serial, tx_busy;
  wire clk, rst_n, baud_tick_16x, tx_start;
  wire [7:0] tx_data;
  wire tx_serial, tx_busy;
  wire [2:0] bit_idx;
  wire [7:0] data_reg;
  wire [2:0] state;
  wire [3:0] tick_cnt;
  wire UNCONNECTED0, n_0, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, parity_bit;
  wire tx_busy_211, tx_serial_210;
  dfcrq4 \bit_idx_reg[0] (.CDN (rst_n), .CP (clk), .D (n_60), .Q
       (bit_idx[0]));
  dfcrq4 \bit_idx_reg[2] (.CDN (rst_n), .CP (clk), .D (n_63), .Q
       (bit_idx[2]));
  decrq1 \data_reg_reg[0] (.CDN (rst_n), .CP (clk), .D (tx_data[0]),
       .ENN (n_35), .Q (data_reg[0]));
  decrq1 \data_reg_reg[1] (.CDN (rst_n), .CP (clk), .D (tx_data[1]),
       .ENN (n_35), .Q (data_reg[1]));
  decrq1 \data_reg_reg[2] (.CDN (rst_n), .CP (clk), .D (tx_data[2]),
       .ENN (n_35), .Q (data_reg[2]));
  decrq1 \data_reg_reg[3] (.CDN (rst_n), .CP (clk), .D (tx_data[3]),
       .ENN (n_35), .Q (data_reg[3]));
  decrq1 \data_reg_reg[4] (.CDN (rst_n), .CP (clk), .D (tx_data[4]),
       .ENN (n_35), .Q (data_reg[4]));
  decrq1 \data_reg_reg[5] (.CDN (rst_n), .CP (clk), .D (tx_data[5]),
       .ENN (n_35), .Q (data_reg[5]));
  decrq1 \data_reg_reg[6] (.CDN (rst_n), .CP (clk), .D (tx_data[6]),
       .ENN (n_35), .Q (data_reg[6]));
  decrq1 \data_reg_reg[7] (.CDN (rst_n), .CP (clk), .D (tx_data[7]),
       .ENN (n_35), .Q (data_reg[7]));
  decrq1 parity_bit_reg(.CDN (rst_n), .CP (clk), .D (n_68), .ENN
       (n_35), .Q (parity_bit));
  decrq1 \state_reg[0] (.CDN (rst_n), .CP (clk), .D (n_16), .ENN
       (n_66), .Q (state[0]));
  sdcrq4 \state_reg[1] (.CDN (rst_n), .CP (clk), .D (state[1]), .SD
       (n_28), .SC (n_67), .Q (state[1]));
  sdcrq1 \tick_cnt_reg[0] (.CDN (rst_n), .CP (clk), .D (n_48), .SD
       (n_39), .SC (tick_cnt[0]), .Q (tick_cnt[0]));
  dfcrq2 \tick_cnt_reg[2] (.CDN (rst_n), .CP (clk), .D (n_61), .Q
       (tick_cnt[2]));
  dfcrq2 \tick_cnt_reg[3] (.CDN (rst_n), .CP (clk), .D (n_62), .Q
       (tick_cnt[3]));
  dfcrq1 tx_busy_reg(.CDN (rst_n), .CP (clk), .D (n_57), .Q
       (tx_busy_211));
  dfprb2 tx_serial_reg(.SDN (rst_n), .CP (clk), .D (n_71), .Q
       (tx_serial_210), .QN (UNCONNECTED0));
  aor221d1 g2099__9315(.A (n_13), .B1 (n_65), .B2 (state[1]), .C1
       (state[2]), .C2 (tx_serial_210), .Z (n_71));
  oaim21d1 g2101__9945(.A (n_69), .B1 (n_66), .B2 (state[2]), .ZN
       (n_70));
  nd03d1 g2102__2883(.A1 (n_67), .A2 (n_17), .A3 (state[1]), .ZN
       (n_69));
  xr03d1 g2103__2346(.A1 (n_49), .A2 (n_37), .A3 (tx_data[7]), .Z
       (n_68));
  inv0d1 g2106(.I (n_67), .ZN (n_66));
  aor22d1 g2107__1666(.A1 (n_58), .A2 (n_16), .B1 (n_17), .B2
       (parity_bit), .Z (n_65));
  oai211d2 g2108__7410(.A (n_35), .B (n_27), .C1 (n_31), .C2 (n_51),
       .ZN (n_67));
  oaim31d1 g2113__6417(.A (n_56), .B1 (n_48), .B2 (n_11), .B3
       (tick_cnt[0]), .ZN (n_64));
  mx02d1 g2114__5477(.I0 (bit_idx[2]), .I1 (n_55), .S (n_47), .Z
       (n_63));
  oaim21d1 g2117__2398(.A (n_53), .B1 (n_48), .B2 (n_32), .ZN (n_62));
  oaim21d1 g2118__5107(.A (n_54), .B1 (n_48), .B2 (n_23), .ZN (n_61));
  mx02d1 g2119__6260(.I0 (bit_idx[0]), .I1 (n_29), .S (n_47), .Z
       (n_60));
  aor31d1 g2120__4319(.A (n_52), .B1 (n_47), .B2 (n_24), .B3 (n_33), .Z
       (n_59));
  aor31d1 g2121__8428(.A (n_50), .B1 (n_19), .B2 (n_5), .B3
       (bit_idx[1]), .Z (n_58));
  mx02d1 g2122__5526(.I0 (tx_busy_211), .I1 (n_34), .S (n_41), .Z
       (n_57));
  nd02d0 g2131__6783(.A1 (n_44), .A2 (tick_cnt[1]), .ZN (n_56));
  nr02d1 g2132__3680(.A1 (n_0), .A2 (n_42), .ZN (n_55));
  nd12d1 g2133__1617(.A1 (n_45), .A2 (tick_cnt[2]), .ZN (n_54));
  nd12d1 g2134__2802(.A1 (n_46), .A2 (tick_cnt[3]), .ZN (n_53));
  nr02d1 g2135__1705(.A1 (n_7), .A2 (n_47), .ZN (n_52));
  an02d1 g2136__5122(.A1 (n_43), .A2 (n_16), .Z (n_51));
  aor22d1 g2137__8246(.A1 (n_38), .A2 (n_7), .B1 (n_36), .B2 (n_20), .Z
       (n_50));
  xr03d1 g2138__7098(.A1 (n_18), .A2 (tx_data[6]), .A3 (tx_data[3]), .Z
       (n_49));
  aoim21d1 g2139__6131(.A (n_39), .B1 (n_4), .B2 (n_26), .ZN (n_46));
  aoim21d1 g2140__1881(.A (n_39), .B1 (n_4), .B2 (n_15), .ZN (n_45));
  an02d2 g2141__5115(.A1 (n_40), .A2 (n_22), .Z (n_48));
  oai21d2 g2142__7482(.A (n_22), .B1 (n_31), .B2 (n_0), .ZN (n_47));
  oaim21d1 g2143__4733(.A (n_40), .B1 (n_22), .B2 (n_9), .ZN (n_44));
  nd03d1 g2144__6161(.A1 (n_36), .A2 (bit_idx[2]), .A3 (state[1]), .ZN
       (n_43));
  mx02d1 g2145__9315(.I0 (n_10), .I1 (bit_idx[2]), .S (n_36), .Z
       (n_42));
  oaim21d1 g2146__9945(.A (n_22), .B1 (n_30), .B2 (n_13), .ZN (n_41));
  inv0d1 g2147(.I (n_39), .ZN (n_40));
  aoi21d4 g2148__2883(.A (n_4), .B1 (n_27), .B2 (baud_tick_16x), .ZN
       (n_39));
  mx04d2 g2149__2346(.I0 (data_reg[0]), .I1 (data_reg[4]), .I2
       (data_reg[1]), .I3 (data_reg[5]), .S0 (bit_idx[2]), .S1
       (bit_idx[0]), .Z (n_38));
  xr03d1 g2150__1666(.A1 (tx_data[0]), .A2 (tx_data[4]), .A3
       (tx_data[2]), .Z (n_37));
  inv0d1 g2151(.I (n_35), .ZN (n_34));
  ah01d2 g2152__7410(.A (bit_idx[0]), .B (bit_idx[1]), .CO (n_36), .S
       (n_33));
  nr02d1 g2153__6417(.A1 (tick_cnt[3]), .A2 (n_25), .ZN (n_32));
  nd02d7 g2154__5477(.A1 (n_3), .A2 (n_4), .ZN (n_35));
  inv0d1 g2155(.I (n_31), .ZN (n_30));
  nr02d1 g2156__2398(.A1 (bit_idx[0]), .A2 (n_0), .ZN (n_29));
  oaim21d1 g2157__5107(.A (n_0), .B1 (n_17), .B2 (n_6), .ZN (n_28));
  nd03d2 g2158__6260(.A1 (baud_tick_16x), .A2 (tick_cnt[3]), .A3
       (n_26), .ZN (n_31));
  inv0d1 g2159(.I (n_25), .ZN (n_26));
  inv0d1 g2160(.I (n_0), .ZN (n_24));
  nr02d1 g2161__4319(.A1 (tick_cnt[2]), .A2 (n_14), .ZN (n_23));
  nd12d1 g2162__8428(.A1 (n_13), .A2 (state[2]), .ZN (n_27));
  nd02d2 g2163__5526(.A1 (n_15), .A2 (tick_cnt[2]), .ZN (n_25));
  inv0d1 g2165(.I (n_22), .ZN (n_21));
  mx02d1 g2166__6783(.I0 (data_reg[7]), .I1 (data_reg[3]), .S (n_10),
       .Z (n_20));
  mx02d1 g2167__3680(.I0 (data_reg[2]), .I1 (data_reg[6]), .S
       (bit_idx[2]), .Z (n_19));
  xr02d1 g2168__1617(.A1 (tx_data[5]), .A2 (tx_data[1]), .Z (n_18));
  or02d2 g2169__2802(.A1 (n_12), .A2 (state[2]), .Z (n_22));
  an02d2 g2171__1705(.A1 (n_8), .A2 (state[0]), .Z (n_17));
  an12d2 g2172__5122(.A1 (state[0]), .A2 (n_8), .Z (n_16));
  inv0d1 g2173(.I (n_14), .ZN (n_15));
  inv0d1 g2174(.I (n_13), .ZN (n_12));
  or02d1 g2175__8246(.A1 (n_9), .A2 (n_11), .Z (n_14));
  an12d2 g2176__7098(.A1 (state[0]), .A2 (n_6), .Z (n_13));
  inv0d1 g2178(.I (bit_idx[2]), .ZN (n_10));
  inv0d1 g2179(.I (tick_cnt[0]), .ZN (n_9));
  inv0d2 g2182(.I (state[1]), .ZN (n_6));
  inv0d1 g2183(.I (bit_idx[0]), .ZN (n_5));
  buffd1 drc_bufs(.I (tx_start), .Z (n_3));
  buffd4 drc_bufs2214(.I (tx_busy_211), .Z (tx_busy));
  buffd4 drc_bufs2218(.I (tx_serial_210), .Z (tx_serial));
  buffd3 drc2235(.I (n_21), .Z (n_4));
  nd12d4 g2__6131(.A1 (n_6), .A2 (n_16), .ZN (n_0));
  dfcrb1 \tick_cnt_reg[1] (.CDN (rst_n), .CP (clk), .D (n_64), .Q
       (tick_cnt[1]), .QN (n_11));
  dfcrb2 \state_reg[2] (.CDN (rst_n), .CP (clk), .D (n_70), .Q
       (state[2]), .QN (n_8));
  dfcrb2 \bit_idx_reg[1] (.CDN (rst_n), .CP (clk), .D (n_59), .Q
       (bit_idx[1]), .QN (n_7));
endmodule

module uart_top_CLK_FREQ50000000_BAUD_RATE9600(clk, rst_n, tx_start,
     tx_data, tx_busy, rx_data, rx_done, parity_error, framing_error,
     tx_serial, rx_serial);
  input clk, rst_n, tx_start, rx_serial;
  input [7:0] tx_data;
  output tx_busy, rx_done, parity_error, framing_error, tx_serial;
  output [7:0] rx_data;
  wire clk, rst_n, tx_start, rx_serial;
  wire [7:0] tx_data;
  wire tx_busy, rx_done, parity_error, framing_error, tx_serial;
  wire [7:0] rx_data;
  wire baud_tick_16x;
  baud_gen_CLK_FREQ50000000_BAUD_RATE9600 u_baud_gen(.clk (clk), .rst_n
       (rst_n), .baud_tick_16x (baud_tick_16x));
  uart_rx u_uart_rx(.clk (clk), .rst_n (rst_n), .baud_tick_16x
       (baud_tick_16x), .rx_serial (rx_serial), .rx_data (rx_data),
       .rx_done (rx_done), .parity_error (parity_error), .framing_error
       (framing_error));
  uart_tx u_uart_tx(.clk (clk), .rst_n (rst_n), .baud_tick_16x
       (baud_tick_16x), .tx_start (tx_start), .tx_data (tx_data),
       .tx_serial (tx_serial), .tx_busy (tx_busy));
endmodule

module uart_top_pad(CLK_PAD, RST_N_PAD, TX_START_PAD, TX_DATA_PAD,
     TX_BUSY_PAD, RX_DATA_PAD, RX_DONE_PAD, PARITY_ERROR_PAD,
     FRAMING_ERROR_PAD, TX_SERIAL_PAD, RX_SERIAL_PAD);
  input CLK_PAD, RST_N_PAD, TX_START_PAD, RX_SERIAL_PAD;
  input [7:0] TX_DATA_PAD;
  output TX_BUSY_PAD, RX_DONE_PAD, PARITY_ERROR_PAD, FRAMING_ERROR_PAD,
       TX_SERIAL_PAD;
  output [7:0] RX_DATA_PAD;
  wire CLK_PAD, RST_N_PAD, TX_START_PAD, RX_SERIAL_PAD;
  wire [7:0] TX_DATA_PAD;
  wire TX_BUSY_PAD, RX_DONE_PAD, PARITY_ERROR_PAD, FRAMING_ERROR_PAD,
       TX_SERIAL_PAD;
  wire [7:0] RX_DATA_PAD;
  wire [7:0] rx_data_core;
  wire [7:0] tx_data_core;
  wire clk_core, clk_pad_to_buf, framing_error_core, n_28, n_31, n_34,
       n_37, n_40;
  wire n_43, n_46, n_49, n_85, n_109, parity_error_core, rst_n_core,
       rx_done_core;
  wire rx_serial_core, tx_busy_core, tx_serial_core, tx_start_core;
  uart_top_CLK_FREQ50000000_BAUD_RATE9600 u_uart_top(.clk (clk_core),
       .rst_n (rst_n_core), .tx_start (tx_start_core), .tx_data ({n_43,
       n_28, n_34, n_31, n_46, n_49, n_40, n_37}), .tx_busy
       (tx_busy_core), .rx_data (rx_data_core), .rx_done
       (rx_done_core), .parity_error (parity_error_core),
       .framing_error (framing_error_core), .tx_serial
       (tx_serial_core), .rx_serial (rx_serial_core));
  pc3o01 \g_rx_data_pads[0].u_pad_rx_data (.I (rx_data_core[0]), .PAD
       (RX_DATA_PAD[0]));
  pc3o01 \g_rx_data_pads[1].u_pad_rx_data (.I (rx_data_core[1]), .PAD
       (RX_DATA_PAD[1]));
  pc3o01 \g_rx_data_pads[2].u_pad_rx_data (.I (rx_data_core[2]), .PAD
       (RX_DATA_PAD[2]));
  pc3o01 \g_rx_data_pads[3].u_pad_rx_data (.I (rx_data_core[3]), .PAD
       (RX_DATA_PAD[3]));
  pc3o01 \g_rx_data_pads[4].u_pad_rx_data (.I (rx_data_core[4]), .PAD
       (RX_DATA_PAD[4]));
  pc3o01 \g_rx_data_pads[5].u_pad_rx_data (.I (rx_data_core[5]), .PAD
       (RX_DATA_PAD[5]));
  pc3o01 \g_rx_data_pads[6].u_pad_rx_data (.I (rx_data_core[6]), .PAD
       (RX_DATA_PAD[6]));
  pc3o01 \g_rx_data_pads[7].u_pad_rx_data (.I (rx_data_core[7]), .PAD
       (RX_DATA_PAD[7]));
  pc3d01 \g_tx_data_pads[0].u_pad_tx_data (.PAD (TX_DATA_PAD[0]), .CIN
       (tx_data_core[0]));
  pc3d01 \g_tx_data_pads[1].u_pad_tx_data (.PAD (TX_DATA_PAD[1]), .CIN
       (tx_data_core[1]));
  pc3d01 \g_tx_data_pads[2].u_pad_tx_data (.PAD (TX_DATA_PAD[2]), .CIN
       (tx_data_core[2]));
  pc3d01 \g_tx_data_pads[3].u_pad_tx_data (.PAD (TX_DATA_PAD[3]), .CIN
       (tx_data_core[3]));
  pc3d01 \g_tx_data_pads[4].u_pad_tx_data (.PAD (TX_DATA_PAD[4]), .CIN
       (tx_data_core[4]));
  pc3d01 \g_tx_data_pads[5].u_pad_tx_data (.PAD (TX_DATA_PAD[5]), .CIN
       (tx_data_core[5]));
  pc3d01 \g_tx_data_pads[6].u_pad_tx_data (.PAD (TX_DATA_PAD[6]), .CIN
       (tx_data_core[6]));
  pc3d01 \g_tx_data_pads[7].u_pad_tx_data (.PAD (TX_DATA_PAD[7]), .CIN
       (tx_data_core[7]));
  pc3c01 u_clkbuf(.CCLK (n_109), .CP (clk_core));
  pc3d01 u_pad_clk(.PAD (CLK_PAD), .CIN (clk_pad_to_buf));
  pc3o01 u_pad_framing_error(.I (framing_error_core), .PAD
       (FRAMING_ERROR_PAD));
  pc3o01 u_pad_parity_error(.I (parity_error_core), .PAD
       (PARITY_ERROR_PAD));
  pc3d01u u_pad_rst_n(.PAD (RST_N_PAD), .CIN (rst_n_core));
  pc3o01 u_pad_rx_done(.I (rx_done_core), .PAD (RX_DONE_PAD));
  pc3d01 u_pad_rx_serial(.PAD (RX_SERIAL_PAD), .CIN (rx_serial_core));
  pc3o01 u_pad_tx_busy(.I (tx_busy_core), .PAD (TX_BUSY_PAD));
  pc3o01 u_pad_tx_serial(.I (tx_serial_core), .PAD (TX_SERIAL_PAD));
  pc3d01 u_pad_tx_start(.PAD (TX_START_PAD), .CIN (tx_start_core));
  buffd1 drc_bufs18(.I (tx_data_core[7]), .Z (n_43));
  buffd1 drc_bufs21(.I (tx_data_core[3]), .Z (n_46));
  buffd1 drc_bufs24(.I (tx_data_core[2]), .Z (n_49));
  buffd1 drc_bufs36(.I (tx_data_core[0]), .Z (n_37));
  buffd1 drc_bufs39(.I (tx_data_core[6]), .Z (n_28));
  buffd1 drc_bufs42(.I (tx_data_core[1]), .Z (n_40));
  buffd1 drc_bufs45(.I (tx_data_core[5]), .Z (n_34));
  buffd1 drc_bufs48(.I (tx_data_core[4]), .Z (n_31));
  buffd1 drc_bufs60(.I (clk_pad_to_buf), .Z (n_85));
  buffda drc(.I (n_85), .Z (n_109));
endmodule

