/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ece.nitw.ac.in)
#  Generated on:      Mon Jun 29 17:31:57 2026
#  Design:            uart_top
#  Command:           saveNetlist ./Signoff/UART_signoff_withPG.v
###############################################################
*/
module uart_top (
	clk, 
	rst_n, 
	tx_start, 
	tx_data, 
	tx_busy, 
	rx_data, 
	rx_done, 
	parity_error, 
	framing_error, 
	tx_serial, 
	rx_serial);
   input clk;
   input rst_n;
   input tx_start;
   input [7:0] tx_data;
   output tx_busy;
   output [7:0] rx_data;
   output rx_done;
   output parity_error;
   output framing_error;
   output tx_serial;
   input rx_serial;

   // Internal wires
   wire FE_OFN207_n_165;
   wire FE_OFN206_n_189;
   wire FE_OFN205_n_59;
   wire FE_OFN204_n_111;
   wire FE_OFN203_n_177;
   wire FE_OFN202_n_126;
   wire FE_OFN201_n_362;
   wire FE_OFN200_n_155;
   wire FE_OFN199_n_190;
   wire FE_OFN198_n_182;
   wire FE_OFN197_n_210;
   wire FE_OFN196_n_176;
   wire FE_OFN195_n_117;
   wire FE_OFN194_n_127;
   wire FE_OFN191_u_uart_rx_state_1;
   wire FE_OFN190_n_183;
   wire FE_OFN189_n_183;
   wire FE_OFN188_u_baud_gen_count_8;
   wire FE_OFN187_u_uart_tx_state_2;
   wire FE_OFN185_n_107;
   wire FE_OFN183_u_uart_rx_bit_idx_2;
   wire FE_OFN139_n_120;
   wire FE_OFN182_n_201;
   wire FE_OFN181_baud_tick_16x;
   wire FE_OFN180_n_188;
   wire FE_OFN179_n_188;
   wire FE_OFN177_n_175;
   wire FE_OFN176_n_149;
   wire FE_OFN175_n_122;
   wire FE_OFN174_n_0;
   wire FE_OFN173_u_uart_tx_data_reg_6;
   wire FE_OFN172_n_87;
   wire FE_OFN171_u_uart_rx_bit_idx_0;
   wire FE_OFN170_n_369;
   wire FE_OFN169_n_197;
   wire FE_OFN168_n_147;
   wire FE_OFN167_u_uart_tx_tick_cnt_1;
   wire FE_OFN166_n_25;
   wire FE_OFN164_n_170;
   wire FE_OFN163_n_20;
   wire FE_OFN162_n_31;
   wire FE_OFN161_n_200;
   wire FE_OFN159_n_47;
   wire FE_OFN157_u_uart_tx_data_reg_0;
   wire FE_OFN155_u_uart_rx_tick_cnt_1;
   wire FE_OFN154_n;
   wire FE_OFN131_n_208;
   wire FE_OFN128_n_188;
   wire FE_OFN127_n_188;
   wire FE_OFN123_n_164;
   wire FE_OFN119_n_207;
   wire FE_OFN118_n_181;
   wire FE_OFN117_n_179;
   wire FE_OFN116_n_179;
   wire FE_OFN114_n_154;
   wire FE_OFN113_n_142;
   wire FE_OFN112_n_140;
   wire FE_OFN111_n_121;
   wire FE_OFN110_n_120;
   wire FE_OFN107_n_103;
   wire FE_OFN106_n_204;
   wire FE_OFN104_n_161;
   wire FE_OFN103_n_158;
   wire FE_OFN102_n_150;
   wire FE_OFN101_n_138;
   wire FE_OFN100_n_132;
   wire FE_OFN99_n_125;
   wire FE_OFN98_n_118;
   wire FE_OFN97_n_118;
   wire FE_OFN96_n_113;
   wire FE_OFN95_n_100;
   wire FE_OFN94_n_82;
   wire FE_OFN92_n_191;
   wire FE_OFN91_n_177;
   wire FE_OFN90_n_174;
   wire FE_OFN89_n_157;
   wire FE_OFN86_n_108;
   wire FE_OFN85_n_99;
   wire FE_OFN84_n_94;
   wire FE_OFN81_n_359;
   wire FE_OFN80_n_199;
   wire FE_OFN79_n_192;
   wire FE_OFN77_n_172;
   wire FE_OFN76_n_168;
   wire FE_OFN75_n_153;
   wire FE_OFN74_n_110;
   wire FE_OFN73_n_96;
   wire FE_OFN72_n_89;
   wire FE_OFN70_n_66;
   wire FE_OFN69_n_63;
   wire FE_OFN68_n_54;
   wire FE_OFN67_n_50;
   wire FE_OFN66_n_49;
   wire FE_OFN64_n_360;
   wire FE_OFN63_n_148;
   wire FE_OFN62_n_127;
   wire FE_OFN61_n_83;
   wire FE_OFN60_n_73;
   wire FE_OFN59_n_68;
   wire FE_OFN58_n_58;
   wire FE_OFN57_n_57;
   wire FE_OFN56_n_55;
   wire FE_OFN55_n_33;
   wire FE_OFN54_n_22;
   wire FE_OFN53_n_18;
   wire FE_OFN52_n_14;
   wire FE_OFN50_u_uart_rx_rx_sync_ff2;
   wire FE_OFN49_u_uart_rx_parity_calc;
   wire FE_OFN48_n_337;
   wire FE_OFN47_n_126;
   wire FE_OFN46_n_122;
   wire FE_OFN45_n_87;
   wire FE_OFN44_n_32;
   wire FE_OFN43_n_25;
   wire FE_OFN42_n_24;
   wire FE_OFN41_n_9;
   wire FE_OFN39_n_5;
   wire FE_OFN38_n_2;
   wire FE_OFN37_n_1;
   wire FE_OFN36_baud_tick_16x;
   wire FE_OFN34_u_uart_tx_data_reg_3;
   wire FE_OFN32_u_uart_tx_tick_cnt_0;
   wire FE_OFN31_u_uart_tx_tick_cnt_1;
   wire FE_OFN30_u_uart_tx_tick_cnt_3;
   wire FE_OFN29_u_uart_tx_bit_idx_0;
   wire FE_OFN28_u_uart_tx_bit_idx_1;
   wire FE_OFN27_u_uart_tx_bit_idx_2;
   wire FE_OFN26_u_uart_rx_data_reg_0;
   wire FE_OFN25_u_uart_rx_data_reg_1;
   wire FE_OFN24_u_uart_rx_data_reg_2;
   wire FE_OFN23_u_uart_rx_data_reg_3;
   wire FE_OFN22_u_uart_rx_data_reg_4;
   wire FE_OFN21_u_uart_rx_data_reg_5;
   wire FE_OFN20_u_uart_rx_data_reg_6;
   wire FE_OFN19_u_uart_rx_data_reg_7;
   wire FE_OFN18_u_uart_tx_state_0;
   wire FE_OFN17_u_uart_tx_state_1;
   wire FE_OFN16_u_uart_tx_state_2;
   wire FE_OFN15_u_uart_rx_tick_cnt_0;
   wire FE_OFN14_u_uart_rx_tick_cnt_1;
   wire FE_OFN13_u_uart_rx_tick_cnt_2;
   wire FE_OFN12_u_uart_rx_tick_cnt_3;
   wire FE_OFN11_u_uart_rx_bit_idx_0;
   wire FE_OFN10_u_uart_rx_bit_idx_1;
   wire FE_OFN9_u_uart_rx_bit_idx_2;
   wire FE_OFN8_u_uart_rx_state_0;
   wire FE_OFN7_u_uart_rx_state_1;
   wire FE_OFN6_u_uart_rx_state_2;
   wire FE_OFN5_u_baud_gen_count_0;
   wire FE_OFN4_u_baud_gen_count_1;
   wire FE_OFN3_u_baud_gen_count_3;
   wire FE_OFN2_u_baud_gen_count_4;
   wire FE_OFN1_u_baud_gen_count_5;
   wire FE_OFN0_u_baud_gen_count_7;
   wire [8:0] u_baud_gen_count;
   wire [2:0] u_uart_rx_state;
   wire [2:0] u_uart_rx_bit_idx;
   wire [3:0] u_uart_rx_tick_cnt;
   wire [2:0] u_uart_tx_state;
   wire [7:0] u_uart_rx_data_reg;
   wire [2:0] u_uart_tx_bit_idx;
   wire [3:0] u_uart_tx_tick_cnt;
   wire [7:0] u_uart_tx_data_reg;
   wire baud_tick_16x;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_12;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_49;
   wire n_50;
   wire n_52;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_115;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_130;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_207;
   wire n_208;
   wire n_210;
   wire n_212;
   wire n_213;
   wire n_337;
   wire n_357;
   wire n_358;
   wire n_359;
   wire n_360;
   wire n_361;
   wire n_362;
   wire n_363;
   wire n_369;
   wire u_uart_rx_parity_calc;
   wire u_uart_rx_rx_sync_ff1;
   wire u_uart_rx_rx_sync_ff2;
   wire u_uart_tx_parity_bit;

   CLKBUFX6M FE_OFC185_n_165 (.A(n_165),
	.Y(FE_OFN207_n_165));
   BUFX4M FE_OFC184_n_189 (.A(n_189),
	.Y(FE_OFN206_n_189));
   BUFX2M FE_OFC183_n_59 (.A(n_59),
	.Y(FE_OFN205_n_59));
   BUFX2M FE_OFC182_n_111 (.A(n_111),
	.Y(FE_OFN204_n_111));
   BUFX2M FE_OFC181_n_177 (.A(n_177),
	.Y(FE_OFN203_n_177));
   BUFX2M FE_OFC180_n_126 (.A(n_126),
	.Y(FE_OFN202_n_126));
   BUFX2M FE_OFC179_n_362 (.A(n_362),
	.Y(FE_OFN201_n_362));
   BUFX2M FE_OFC178_n_155 (.A(n_155),
	.Y(FE_OFN200_n_155));
   BUFX2M FE_OFC177_n_190 (.A(n_190),
	.Y(FE_OFN199_n_190));
   BUFX2M FE_OFC176_n_182 (.A(n_182),
	.Y(FE_OFN198_n_182));
   BUFX2M FE_OFC175_n_210 (.A(n_210),
	.Y(FE_OFN197_n_210));
   BUFX2M FE_OFC174_n_176 (.A(n_176),
	.Y(FE_OFN196_n_176));
   BUFX2M FE_OFC173_n_117 (.A(n_117),
	.Y(FE_OFN195_n_117));
   BUFX2M FE_OFC172_n_127 (.A(n_127),
	.Y(FE_OFN194_n_127));
   BUFX2M FE_OFC169_u_uart_rx_state_1 (.A(u_uart_rx_state[1]),
	.Y(FE_OFN191_u_uart_rx_state_1));
   INVXLM FE_OFC168_n_183 (.A(FE_OFN189_n_183),
	.Y(FE_OFN190_n_183));
   INVXLM FE_OFC167_n_183 (.A(n_183),
	.Y(FE_OFN189_n_183));
   BUFX2M FE_OFC166_u_baud_gen_count_8 (.A(u_baud_gen_count[8]),
	.Y(FE_OFN188_u_baud_gen_count_8));
   BUFX2M FE_OFC165_u_uart_tx_state_2 (.A(u_uart_tx_state[2]),
	.Y(FE_OFN187_u_uart_tx_state_2));
   BUFX2M FE_OFC163_n_107 (.A(n_107),
	.Y(FE_OFN185_n_107));
   BUFX2M FE_OFC161_u_uart_rx_bit_idx_2 (.A(u_uart_rx_bit_idx[2]),
	.Y(FE_OFN183_u_uart_rx_bit_idx_2));
   CLKBUFX1M FE_OFC139_n_120 (.A(n_120),
	.Y(FE_OFN139_n_120));
   BUFX2M FE_OFC160_n_201 (.A(n_201),
	.Y(FE_OFN182_n_201));
   BUFX2M FE_OFC159_baud_tick_16x (.A(baud_tick_16x),
	.Y(FE_OFN181_baud_tick_16x));
   INVXLM FE_OFC158_n_188 (.A(FE_OFN179_n_188),
	.Y(FE_OFN180_n_188));
   INVXLM FE_OFC157_n_188 (.A(n_188),
	.Y(FE_OFN179_n_188));
   BUFX2M FE_OFC155_n_175 (.A(n_175),
	.Y(FE_OFN177_n_175));
   BUFX2M FE_OFC154_n_149 (.A(n_149),
	.Y(FE_OFN176_n_149));
   BUFX2M FE_OFC153_n_122 (.A(n_122),
	.Y(FE_OFN175_n_122));
   BUFX2M FE_OFC152_n_0 (.A(n_0),
	.Y(FE_OFN174_n_0));
   BUFX2M FE_OFC151_u_uart_tx_data_reg_6 (.A(u_uart_tx_data_reg[6]),
	.Y(FE_OFN173_u_uart_tx_data_reg_6));
   BUFX2M FE_OFC150_n_87 (.A(n_87),
	.Y(FE_OFN172_n_87));
   BUFX2M FE_OFC149_u_uart_rx_bit_idx_0 (.A(u_uart_rx_bit_idx[0]),
	.Y(FE_OFN171_u_uart_rx_bit_idx_0));
   BUFX2M FE_OFC148_n_369 (.A(n_369),
	.Y(FE_OFN170_n_369));
   BUFX2M FE_OFC147_n_197 (.A(n_197),
	.Y(FE_OFN169_n_197));
   BUFX2M FE_OFC146_n_147 (.A(n_147),
	.Y(FE_OFN168_n_147));
   BUFX2M FE_OFC145_u_uart_tx_tick_cnt_1 (.A(u_uart_tx_tick_cnt[1]),
	.Y(FE_OFN167_u_uart_tx_tick_cnt_1));
   BUFX2M FE_OFC144_n_25 (.A(n_25),
	.Y(FE_OFN166_n_25));
   BUFX2M FE_OFC142_n_170 (.A(n_170),
	.Y(FE_OFN164_n_170));
   BUFX2M FE_OFC141_n_20 (.A(n_20),
	.Y(FE_OFN163_n_20));
   BUFX2M FE_OFC140_n_31 (.A(n_31),
	.Y(FE_OFN162_n_31));
   BUFX2M FE_OFC139_n_200 (.A(n_200),
	.Y(FE_OFN161_n_200));
   BUFX4M FE_OFC137_n_47 (.A(n_47),
	.Y(FE_OFN159_n_47));
   CLKBUFX2M FE_OFC135_u_uart_tx_data_reg_0 (.A(u_uart_tx_data_reg[0]),
	.Y(FE_OFN157_u_uart_tx_data_reg_0));
   BUFX2M FE_OFC133_u_uart_rx_tick_cnt_1 (.A(u_uart_rx_tick_cnt[1]),
	.Y(FE_OFN155_u_uart_rx_tick_cnt_1));
   BUFX4M FE_OFC132_n_153 (.A(FE_OFN75_n_153),
	.Y(FE_OFN154_n));
   BUFX2M FE_OFC131_n_208 (.A(n_208),
	.Y(FE_OFN131_n_208));
   INVXLM FE_OFC128_n_188 (.A(FE_OFN127_n_188),
	.Y(FE_OFN128_n_188));
   INVXLM FE_OFC127_n_188 (.A(FE_OFN180_n_188),
	.Y(FE_OFN127_n_188));
   BUFX4M FE_OFC123_n_164 (.A(n_164),
	.Y(FE_OFN123_n_164));
   BUFX2M FE_OFC119_n_207 (.A(n_207),
	.Y(FE_OFN119_n_207));
   CLKBUFX12M FE_OFC118_n_181 (.A(n_181),
	.Y(FE_OFN118_n_181));
   CLKINVX12M FE_OFC117_n_179 (.A(FE_OFN116_n_179),
	.Y(FE_OFN117_n_179));
   INVX4M FE_OFC116_n_179 (.A(n_179),
	.Y(FE_OFN116_n_179));
   BUFX10M FE_OFC114_n_154 (.A(n_154),
	.Y(FE_OFN114_n_154));
   BUFX4M FE_OFC113_n_142 (.A(n_142),
	.Y(FE_OFN113_n_142));
   BUFX4M FE_OFC112_n_140 (.A(n_140),
	.Y(FE_OFN112_n_140));
   BUFX2M FE_OFC111_n_121 (.A(n_121),
	.Y(FE_OFN111_n_121));
   BUFX4M FE_OFC110_n_120 (.A(FE_OFN139_n_120),
	.Y(FE_OFN110_n_120));
   BUFX2M FE_OFC107_n_103 (.A(n_103),
	.Y(FE_OFN107_n_103));
   BUFX4M FE_OFC106_n_204 (.A(n_204),
	.Y(FE_OFN106_n_204));
   BUFX2M FE_OFC104_n_161 (.A(n_161),
	.Y(FE_OFN104_n_161));
   BUFX2M FE_OFC103_n_158 (.A(n_158),
	.Y(FE_OFN103_n_158));
   BUFX2M FE_OFC102_n_150 (.A(n_150),
	.Y(FE_OFN102_n_150));
   BUFX2M FE_OFC101_n_138 (.A(n_138),
	.Y(FE_OFN101_n_138));
   CLKBUFX2M FE_OFC100_n_132 (.A(n_132),
	.Y(FE_OFN100_n_132));
   CLKBUFX2M FE_OFC99_n_125 (.A(n_125),
	.Y(FE_OFN99_n_125));
   BUFX8M FE_OFC98_n_118 (.A(FE_OFN97_n_118),
	.Y(FE_OFN98_n_118));
   CLKBUFX6M FE_OFC97_n_118 (.A(n_118),
	.Y(FE_OFN97_n_118));
   BUFX4M FE_OFC96_n_113 (.A(n_113),
	.Y(FE_OFN96_n_113));
   BUFX2M FE_OFC95_n_100 (.A(n_100),
	.Y(FE_OFN95_n_100));
   CLKBUFX6M FE_OFC94_n_82 (.A(n_82),
	.Y(FE_OFN94_n_82));
   CLKBUFX2M FE_OFC92_n_191 (.A(n_191),
	.Y(FE_OFN92_n_191));
   CLKBUFX2M FE_OFC91_n_177 (.A(FE_OFN203_n_177),
	.Y(FE_OFN91_n_177));
   BUFX8M FE_OFC90_n_174 (.A(n_174),
	.Y(FE_OFN90_n_174));
   BUFX8M FE_OFC89_n_157 (.A(n_157),
	.Y(FE_OFN89_n_157));
   BUFX8M FE_OFC86_n_108 (.A(n_108),
	.Y(FE_OFN86_n_108));
   CLKBUFX6M FE_OFC85_n_99 (.A(n_99),
	.Y(FE_OFN85_n_99));
   BUFX4M FE_OFC84_n_94 (.A(n_94),
	.Y(FE_OFN84_n_94));
   BUFX4M FE_OFC81_n_359 (.A(n_359),
	.Y(FE_OFN81_n_359));
   BUFX8M FE_OFC80_n_199 (.A(n_199),
	.Y(FE_OFN80_n_199));
   BUFX2M FE_OFC79_n_192 (.A(n_192),
	.Y(FE_OFN79_n_192));
   BUFX2M FE_OFC77_n_172 (.A(n_172),
	.Y(FE_OFN77_n_172));
   BUFX8M FE_OFC76_n_168 (.A(n_168),
	.Y(FE_OFN76_n_168));
   BUFX4M FE_OFC75_n_153 (.A(n_153),
	.Y(FE_OFN75_n_153));
   BUFX8M FE_OFC74_n_110 (.A(n_110),
	.Y(FE_OFN74_n_110));
   BUFX4M FE_OFC73_n_96 (.A(n_96),
	.Y(FE_OFN73_n_96));
   BUFX4M FE_OFC72_n_89 (.A(n_89),
	.Y(FE_OFN72_n_89));
   BUFX2M FE_OFC70_n_66 (.A(n_66),
	.Y(FE_OFN70_n_66));
   CLKBUFX2M FE_OFC69_n_63 (.A(n_63),
	.Y(FE_OFN69_n_63));
   BUFX4M FE_OFC68_n_54 (.A(n_54),
	.Y(FE_OFN68_n_54));
   BUFX2M FE_OFC67_n_50 (.A(n_50),
	.Y(FE_OFN67_n_50));
   BUFX4M FE_OFC66_n_49 (.A(n_49),
	.Y(FE_OFN66_n_49));
   CLKBUFX2M FE_OFC64_n_360 (.A(n_360),
	.Y(FE_OFN64_n_360));
   BUFX8M FE_OFC63_n_148 (.A(n_148),
	.Y(FE_OFN63_n_148));
   BUFX4M FE_OFC62_n_127 (.A(FE_OFN194_n_127),
	.Y(FE_OFN62_n_127));
   BUFX4M FE_OFC61_n_83 (.A(n_83),
	.Y(FE_OFN61_n_83));
   BUFX4M FE_OFC60_n_73 (.A(n_73),
	.Y(FE_OFN60_n_73));
   BUFX2M FE_OFC59_n_68 (.A(n_68),
	.Y(FE_OFN59_n_68));
   BUFX4M FE_OFC58_n_58 (.A(n_58),
	.Y(FE_OFN58_n_58));
   BUFX2M FE_OFC57_n_57 (.A(n_57),
	.Y(FE_OFN57_n_57));
   BUFX8M FE_OFC56_n_55 (.A(n_55),
	.Y(FE_OFN56_n_55));
   CLKBUFX4M FE_OFC55_n_33 (.A(n_33),
	.Y(FE_OFN55_n_33));
   CLKBUFX2M FE_OFC54_n_22 (.A(n_22),
	.Y(FE_OFN54_n_22));
   BUFX4M FE_OFC53_n_18 (.A(n_18),
	.Y(FE_OFN53_n_18));
   BUFX4M FE_OFC52_n_14 (.A(n_14),
	.Y(FE_OFN52_n_14));
   BUFX8M FE_OFC50_u_uart_rx_rx_sync_ff2 (.A(u_uart_rx_rx_sync_ff2),
	.Y(FE_OFN50_u_uart_rx_rx_sync_ff2));
   CLKBUFX2M FE_OFC49_u_uart_rx_parity_calc (.A(u_uart_rx_parity_calc),
	.Y(FE_OFN49_u_uart_rx_parity_calc));
   BUFX2M FE_OFC48_n_337 (.A(n_337),
	.Y(FE_OFN48_n_337));
   BUFX4M FE_OFC47_n_126 (.A(FE_OFN202_n_126),
	.Y(FE_OFN47_n_126));
   BUFX4M FE_OFC46_n_122 (.A(FE_OFN175_n_122),
	.Y(FE_OFN46_n_122));
   BUFX4M FE_OFC45_n_87 (.A(FE_OFN172_n_87),
	.Y(FE_OFN45_n_87));
   CLKBUFX6M FE_OFC44_n_32 (.A(n_32),
	.Y(FE_OFN44_n_32));
   BUFX4M FE_OFC43_n_25 (.A(FE_OFN166_n_25),
	.Y(FE_OFN43_n_25));
   BUFX2M FE_OFC42_n_24 (.A(n_24),
	.Y(FE_OFN42_n_24));
   BUFX2M FE_OFC41_n_9 (.A(n_9),
	.Y(FE_OFN41_n_9));
   BUFX2M FE_OFC39_n_5 (.A(n_5),
	.Y(FE_OFN39_n_5));
   BUFX2M FE_OFC38_n_2 (.A(n_2),
	.Y(FE_OFN38_n_2));
   CLKBUFX2M FE_OFC37_n_1 (.A(n_1),
	.Y(FE_OFN37_n_1));
   BUFX8M FE_OFC36_baud_tick_16x (.A(FE_OFN181_baud_tick_16x),
	.Y(FE_OFN36_baud_tick_16x));
   CLKBUFX2M FE_OFC34_u_uart_tx_data_reg_3 (.A(u_uart_tx_data_reg[3]),
	.Y(FE_OFN34_u_uart_tx_data_reg_3));
   BUFX5M FE_OFC32_u_uart_tx_tick_cnt_0 (.A(u_uart_tx_tick_cnt[0]),
	.Y(FE_OFN32_u_uart_tx_tick_cnt_0));
   BUFX4M FE_OFC31_u_uart_tx_tick_cnt_1 (.A(FE_OFN167_u_uart_tx_tick_cnt_1),
	.Y(FE_OFN31_u_uart_tx_tick_cnt_1));
   BUFX4M FE_OFC30_u_uart_tx_tick_cnt_3 (.A(u_uart_tx_tick_cnt[3]),
	.Y(FE_OFN30_u_uart_tx_tick_cnt_3));
   BUFX8M FE_OFC29_u_uart_tx_bit_idx_0 (.A(u_uart_tx_bit_idx[0]),
	.Y(FE_OFN29_u_uart_tx_bit_idx_0));
   BUFX4M FE_OFC28_u_uart_tx_bit_idx_1 (.A(u_uart_tx_bit_idx[1]),
	.Y(FE_OFN28_u_uart_tx_bit_idx_1));
   CLKBUFX6M FE_OFC27_u_uart_tx_bit_idx_2 (.A(u_uart_tx_bit_idx[2]),
	.Y(FE_OFN27_u_uart_tx_bit_idx_2));
   BUFX4M FE_OFC26_u_uart_rx_data_reg_0 (.A(u_uart_rx_data_reg[0]),
	.Y(FE_OFN26_u_uart_rx_data_reg_0));
   BUFX4M FE_OFC25_u_uart_rx_data_reg_1 (.A(u_uart_rx_data_reg[1]),
	.Y(FE_OFN25_u_uart_rx_data_reg_1));
   BUFX4M FE_OFC24_u_uart_rx_data_reg_2 (.A(u_uart_rx_data_reg[2]),
	.Y(FE_OFN24_u_uart_rx_data_reg_2));
   BUFX4M FE_OFC23_u_uart_rx_data_reg_3 (.A(u_uart_rx_data_reg[3]),
	.Y(FE_OFN23_u_uart_rx_data_reg_3));
   BUFX4M FE_OFC22_u_uart_rx_data_reg_4 (.A(u_uart_rx_data_reg[4]),
	.Y(FE_OFN22_u_uart_rx_data_reg_4));
   BUFX4M FE_OFC21_u_uart_rx_data_reg_5 (.A(u_uart_rx_data_reg[5]),
	.Y(FE_OFN21_u_uart_rx_data_reg_5));
   BUFX4M FE_OFC20_u_uart_rx_data_reg_6 (.A(u_uart_rx_data_reg[6]),
	.Y(FE_OFN20_u_uart_rx_data_reg_6));
   BUFX4M FE_OFC19_u_uart_rx_data_reg_7 (.A(u_uart_rx_data_reg[7]),
	.Y(FE_OFN19_u_uart_rx_data_reg_7));
   CLKBUFX6M FE_OFC18_u_uart_tx_state_0 (.A(u_uart_tx_state[0]),
	.Y(FE_OFN18_u_uart_tx_state_0));
   BUFX8M FE_OFC17_u_uart_tx_state_1 (.A(u_uart_tx_state[1]),
	.Y(FE_OFN17_u_uart_tx_state_1));
   BUFX8M FE_OFC16_u_uart_tx_state_2 (.A(FE_OFN187_u_uart_tx_state_2),
	.Y(FE_OFN16_u_uart_tx_state_2));
   BUFX8M FE_OFC15_u_uart_rx_tick_cnt_0 (.A(u_uart_rx_tick_cnt[0]),
	.Y(FE_OFN15_u_uart_rx_tick_cnt_0));
   CLKBUFX6M FE_OFC14_u_uart_rx_tick_cnt_1 (.A(FE_OFN155_u_uart_rx_tick_cnt_1),
	.Y(FE_OFN14_u_uart_rx_tick_cnt_1));
   BUFX4M FE_OFC13_u_uart_rx_tick_cnt_2 (.A(u_uart_rx_tick_cnt[2]),
	.Y(FE_OFN13_u_uart_rx_tick_cnt_2));
   CLKBUFX6M FE_OFC12_u_uart_rx_tick_cnt_3 (.A(u_uart_rx_tick_cnt[3]),
	.Y(FE_OFN12_u_uart_rx_tick_cnt_3));
   BUFX8M FE_OFC11_u_uart_rx_bit_idx_0 (.A(FE_OFN171_u_uart_rx_bit_idx_0),
	.Y(FE_OFN11_u_uart_rx_bit_idx_0));
   BUFX4M FE_OFC10_u_uart_rx_bit_idx_1 (.A(u_uart_rx_bit_idx[1]),
	.Y(FE_OFN10_u_uart_rx_bit_idx_1));
   BUFX8M FE_OFC9_u_uart_rx_bit_idx_2 (.A(FE_OFN183_u_uart_rx_bit_idx_2),
	.Y(FE_OFN9_u_uart_rx_bit_idx_2));
   BUFX4M FE_OFC8_u_uart_rx_state_0 (.A(u_uart_rx_state[0]),
	.Y(FE_OFN8_u_uart_rx_state_0));
   BUFX8M FE_OFC7_u_uart_rx_state_1 (.A(FE_OFN191_u_uart_rx_state_1),
	.Y(FE_OFN7_u_uart_rx_state_1));
   BUFX8M FE_OFC6_u_uart_rx_state_2 (.A(u_uart_rx_state[2]),
	.Y(FE_OFN6_u_uart_rx_state_2));
   CLKBUFX6M FE_OFC5_u_baud_gen_count_0 (.A(u_baud_gen_count[0]),
	.Y(FE_OFN5_u_baud_gen_count_0));
   BUFX4M FE_OFC4_u_baud_gen_count_1 (.A(u_baud_gen_count[1]),
	.Y(FE_OFN4_u_baud_gen_count_1));
   CLKBUFX6M FE_OFC3_u_baud_gen_count_3 (.A(u_baud_gen_count[3]),
	.Y(FE_OFN3_u_baud_gen_count_3));
   BUFX4M FE_OFC2_u_baud_gen_count_4 (.A(u_baud_gen_count[4]),
	.Y(FE_OFN2_u_baud_gen_count_4));
   BUFX4M FE_OFC1_u_baud_gen_count_5 (.A(u_baud_gen_count[5]),
	.Y(FE_OFN1_u_baud_gen_count_5));
   BUFX4M FE_OFC0_u_baud_gen_count_7 (.A(u_baud_gen_count[7]),
	.Y(FE_OFN0_u_baud_gen_count_7));
   XNOR2X8M FE_RC_1_0 (.A(FE_OFN47_n_126),
	.B(FE_OFN62_n_127),
	.Y(n_128));
   XNOR2X8M FE_RC_0_0 (.A(tx_data[5]),
	.B(tx_data[3]),
	.Y(n_31));
   DFFSQX1M u_uart_tx_tx_serial_reg (.D(n_357),
	.CK(clk),
	.SN(rst_n),
	.Q(tx_serial));
   CLKINVX2M g5194 (.A(n_212),
	.Y(n_213));
   DFFRQX2M \u_baud_gen_count_reg[8]  (.D(FE_OFN197_n_210),
	.CK(clk),
	.RN(rst_n),
	.Q(u_baud_gen_count[8]));
   NOR2BX4M g5195__2398 (.AN(FE_OFN119_n_207),
	.B(n_166),
	.Y(n_212));
   DFFRQX2M \u_uart_rx_state_reg[0]  (.D(n_202),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_state[0]));
   NOR2X2M g5178__5107 (.A(n_203),
	.B(FE_OFN80_n_199),
	.Y(n_210));
   DFFRQX2M u_uart_rx_parity_error_reg (.D(n_198),
	.CK(clk),
	.RN(rst_n),
	.Q(parity_error));
   AO22XLM g5208__4319 (.A0(FE_OFN199_n_190),
	.A1(FE_OFN10_u_uart_rx_bit_idx_1),
	.B0(n_144),
	.B1(FE_OFN11_u_uart_rx_bit_idx_0),
	.Y(n_208));
   DFFRQX2M \u_baud_gen_count_reg[7]  (.D(n_196),
	.CK(clk),
	.RN(rst_n),
	.Q(u_baud_gen_count[7]));
   AOI2BB2X4M g5202__8428 (.A0N(n_358),
	.A1N(FE_OFN95_n_100),
	.B0(FE_OFN92_n_191),
	.B1(FE_OFN12_u_uart_rx_tick_cnt_3),
	.Y(n_207));
   DFFRQX2M \u_uart_rx_tick_cnt_reg[2]  (.D(FE_OFN169_n_197),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_tick_cnt[2]));
   AO22X2M g5209__6783 (.A0(FE_OFN77_n_172),
	.A1(FE_OFN17_u_uart_tx_state_1),
	.B0(tx_serial),
	.B1(FE_OFN16_u_uart_tx_state_2),
	.Y(n_205));
   SDFFRQX2M \u_uart_tx_state_reg[0]  (.SI(FE_OFN18_u_uart_tx_state_0),
	.SE(FE_OFN106_n_204),
	.D(FE_OFN53_n_18),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_state[0]));
   SDFFRQX2M \u_uart_tx_state_reg[2]  (.SI(FE_OFN16_u_uart_tx_state_2),
	.SE(FE_OFN106_n_204),
	.D(n_41),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_state[2]));
   SDFFRQX2M \u_uart_tx_state_reg[1]  (.SI(FE_OFN17_u_uart_tx_state_1),
	.SE(FE_OFN106_n_204),
	.D(FE_OFN170_n_369),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_state[1]));
   CLKXOR2X2M g5179__3680 (.A(n_195),
	.B(FE_OFN188_u_baud_gen_count_8),
	.Y(n_203));
   AO21X2M g5253__1617 (.A0(n_98),
	.A1(FE_OFN98_n_118),
	.B0(FE_OFN198_n_182),
	.Y(n_202));
   OAI21X4M g5225__2802 (.A0(FE_OFN123_n_164),
	.A1(n_10),
	.B0(FE_OFN79_n_192),
	.Y(n_201));
   DFFRQX2M \u_uart_rx_data_reg_reg[2]  (.D(FE_OFN190_n_183),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_data_reg[2]));
   DFFRQX2M \u_uart_rx_state_reg[1]  (.D(FE_OFN128_n_188),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_state[1]));
   SDFFRQX2M u_uart_tx_parity_bit_reg (.SI(u_uart_tx_parity_bit),
	.SE(FE_OFN89_n_157),
	.D(n_128),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_parity_bit));
   DFFRQX2M \u_uart_rx_data_reg_reg[6]  (.D(n_167),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_data_reg[6]));
   DFFRQX2M \u_uart_rx_data_reg_reg[0]  (.D(n_169),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_data_reg[0]));
   DFFRQX2M \u_uart_tx_bit_idx_reg[0]  (.D(FE_OFN177_n_175),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_bit_idx[0]));
   NOR2X2M g5184__1705 (.A(n_178),
	.B(FE_OFN80_n_199),
	.Y(n_200));
   NOR2X4M g5221__5122 (.A(FE_OFN201_n_362),
	.B(FE_OFN118_n_181),
	.Y(n_198));
   OAI2BB2X8M g5246__8246 (.A0N(FE_OFN13_u_uart_rx_tick_cnt_2),
	.A1N(n_193),
	.B0(FE_OFN86_n_108),
	.B1(FE_OFN159_n_47),
	.Y(n_197));
   OA21X2M g5182__7098 (.A0(FE_OFN91_n_177),
	.A1(FE_OFN0_u_baud_gen_count_7),
	.B0(n_195),
	.Y(n_196));
   AO22X2M g5258__6131 (.A0(n_193),
	.A1(FE_OFN14_u_uart_rx_tick_cnt_1),
	.B0(n_109),
	.B1(FE_OFN15_u_uart_rx_tick_cnt_0),
	.Y(n_194));
   DFFRQX2M \u_uart_rx_data_reg_reg[3]  (.D(n_171),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_data_reg[3]));
   NAND2BX2M g5247__1881 (.AN(FE_OFN206_n_189),
	.B(n_10),
	.Y(n_192));
   SDFFRQX2M u_uart_tx_tx_busy_reg (.SI(n_78),
	.SE(n_112),
	.D(tx_busy),
	.CK(clk),
	.RN(rst_n),
	.Q(tx_busy));
   DFFRQX2M \u_uart_rx_data_reg_reg[4]  (.D(FE_OFN168_n_147),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_data_reg[4]));
   DFFRQX2M \u_uart_tx_tick_cnt_reg[3]  (.D(n_145),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_tick_cnt[3]));
   DFFRQX2M \u_uart_rx_data_reg_reg[5]  (.D(FE_OFN176_n_149),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_data_reg[5]));
   DFFRQX2M \u_uart_rx_data_reg_reg[1]  (.D(FE_OFN200_n_155),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_data_reg[1]));
   DFFRQX2M \u_uart_rx_tick_cnt_reg[0]  (.D(n_159),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_tick_cnt[0]));
   OAI2BB1X2M g5219__5115 (.A0N(FE_OFN6_u_uart_rx_state_2),
	.A1N(FE_OFN56_n_55),
	.B0(n_152),
	.Y(n_191));
   OAI21X6M g5250__7482 (.A0(FE_OFN11_u_uart_rx_bit_idx_0),
	.A1(n_72),
	.B0(FE_OFN206_n_189),
	.Y(n_190));
   OAI21X4M g5252__4733 (.A0(n_141),
	.A1(FE_OFN6_u_uart_rx_state_2),
	.B0(n_102),
	.Y(n_188));
   OAI2BB1X1M g5255__6161 (.A0N(FE_OFN31_u_uart_tx_tick_cnt_1),
	.A1N(n_136),
	.B0(FE_OFN102_n_150),
	.Y(n_186));
   OAI2BB1X1M g5249__9315 (.A0N(FE_OFN7_u_uart_rx_state_1),
	.A1N(n_163),
	.B0(FE_OFN206_n_189),
	.Y(n_185));
   OAI2BB1X2M g5222__9945 (.A0N(u_uart_tx_tick_cnt[2]),
	.A1N(n_137),
	.B0(FE_OFN104_n_161),
	.Y(n_184));
   OAI21X4M g5281__2883 (.A0(FE_OFN117_n_179),
	.A1(FE_OFN76_n_168),
	.B0(n_156),
	.Y(n_183));
   OAI21X4M g5286__2346 (.A0(n_56),
	.A1(FE_OFN6_u_uart_rx_state_2),
	.B0(FE_OFN207_n_165),
	.Y(n_182));
   SDFFRQX2M \u_uart_rx_rx_data_reg[0]  (.SI(rx_data[0]),
	.SE(FE_OFN118_n_181),
	.D(FE_OFN26_u_uart_rx_data_reg_0),
	.CK(clk),
	.RN(rst_n),
	.Q(rx_data[0]));
   SDFFRQX2M \u_uart_rx_rx_data_reg[4]  (.SI(rx_data[4]),
	.SE(FE_OFN118_n_181),
	.D(FE_OFN22_u_uart_rx_data_reg_4),
	.CK(clk),
	.RN(rst_n),
	.Q(rx_data[4]));
   SDFFRQX2M u_uart_rx_parity_calc_reg (.SI(FE_OFN49_u_uart_rx_parity_calc),
	.SE(n_101),
	.D(FE_OFN50_u_uart_rx_rx_sync_ff2),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_parity_calc));
   SDFFRQX2M \u_uart_rx_rx_data_reg[7]  (.SI(rx_data[7]),
	.SE(FE_OFN118_n_181),
	.D(FE_OFN19_u_uart_rx_data_reg_7),
	.CK(clk),
	.RN(rst_n),
	.Q(rx_data[7]));
   SDFFRQX2M \u_uart_rx_rx_data_reg[5]  (.SI(rx_data[5]),
	.SE(FE_OFN118_n_181),
	.D(FE_OFN21_u_uart_rx_data_reg_5),
	.CK(clk),
	.RN(rst_n),
	.Q(rx_data[5]));
   SDFFRQX2M \u_uart_rx_rx_data_reg[6]  (.SI(rx_data[6]),
	.SE(FE_OFN118_n_181),
	.D(FE_OFN20_u_uart_rx_data_reg_6),
	.CK(clk),
	.RN(rst_n),
	.Q(rx_data[6]));
   SDFFRQX2M \u_uart_rx_rx_data_reg[1]  (.SI(rx_data[1]),
	.SE(FE_OFN118_n_181),
	.D(FE_OFN25_u_uart_rx_data_reg_1),
	.CK(clk),
	.RN(rst_n),
	.Q(rx_data[1]));
   SDFFRQX2M \u_uart_rx_rx_data_reg[2]  (.SI(rx_data[2]),
	.SE(FE_OFN118_n_181),
	.D(FE_OFN24_u_uart_rx_data_reg_2),
	.CK(clk),
	.RN(rst_n),
	.Q(rx_data[2]));
   SDFFRQX2M \u_uart_rx_rx_data_reg[3]  (.SI(rx_data[3]),
	.SE(FE_OFN118_n_181),
	.D(FE_OFN23_u_uart_rx_data_reg_3),
	.CK(clk),
	.RN(rst_n),
	.Q(rx_data[3]));
   DFFRQX2M \u_baud_gen_count_reg[5]  (.D(n_134),
	.CK(clk),
	.RN(rst_n),
	.Q(u_baud_gen_count[5]));
   SDFFRQX2M \u_uart_tx_tick_cnt_reg[0]  (.SI(n_85),
	.SE(FE_OFN32_u_uart_tx_tick_cnt_0),
	.D(n_160),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_tick_cnt[0]));
   OAI21X6M g5267__1666 (.A0(FE_OFN117_n_179),
	.A1(FE_OFN63_n_148),
	.B0(FE_OFN110_n_120),
	.Y(n_180));
   DFFRQX2M u_uart_rx_framing_error_reg (.D(n_135),
	.CK(clk),
	.RN(rst_n),
	.Q(framing_error));
   AO21X1M g5187__7410 (.A0(n_133),
	.A1(FE_OFN46_n_122),
	.B0(FE_OFN91_n_177),
	.Y(n_178));
   OAI21X4M g5259__6417 (.A0(FE_OFN90_n_174),
	.A1(FE_OFN45_n_87),
	.B0(FE_OFN101_n_138),
	.Y(n_176));
   OAI21X4M g5260__5477 (.A0(FE_OFN90_n_174),
	.A1(n_124),
	.B0(FE_OFN99_n_125),
	.Y(n_175));
   OAI2BB1X1M g5254__5107 (.A0N(u_uart_tx_parity_bit),
	.A1N(n_15),
	.B0(n_130),
	.Y(n_172));
   OAI21X8M g5270__6260 (.A0(FE_OFN117_n_179),
	.A1(FE_OFN154_n),
	.B0(FE_OFN112_n_140),
	.Y(n_171));
   OAI21X4M g5223__4319 (.A0(FE_OFN90_n_174),
	.A1(FE_OFN37_n_1),
	.B0(FE_OFN100_n_132),
	.Y(n_170));
   OAI21X8M g5284__8428 (.A0(FE_OFN114_n_154),
	.A1(FE_OFN76_n_168),
	.B0(n_123),
	.Y(n_169));
   OAI21X8M g5279__5526 (.A0(FE_OFN117_n_179),
	.A1(n_146),
	.B0(FE_OFN113_n_142),
	.Y(n_167));
   NAND2X2M g5183__6783 (.A(FE_OFN91_n_177),
	.B(FE_OFN0_u_baud_gen_count_7),
	.Y(n_195));
   DFFRQX2M u_uart_rx_rx_done_reg (.D(n_166),
	.CK(clk),
	.RN(rst_n),
	.Q(rx_done));
   OR3X2M g5320__3680 (.A(FE_OFN123_n_164),
	.B(n_163),
	.C(n_6),
	.Y(n_165));
   DFFRQX2M \u_uart_rx_state_reg[2]  (.D(FE_OFN195_n_117),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_state[2]));
   NAND4X6M g5248__2802 (.A(n_160),
	.B(FE_OFN43_n_25),
	.C(FE_OFN32_u_uart_tx_tick_cnt_0),
	.D(FE_OFN31_u_uart_tx_tick_cnt_1),
	.Y(n_161));
   AO21XLM g5316__1705 (.A0(n_80),
	.A1(FE_OFN15_u_uart_rx_tick_cnt_0),
	.B0(FE_OFN103_n_158),
	.Y(n_159));
   NAND2BX4M g5298__5122 (.AN(FE_OFN103_n_158),
	.B(n_79),
	.Y(n_193));
   AND4X2M g5193__8246 (.A(n_157),
	.B(FE_OFN204_n_111),
	.C(n_363),
	.D(n_69),
	.Y(n_204));
   NAND2X2M g5292__7098 (.A(n_105),
	.B(FE_OFN24_u_uart_rx_data_reg_2),
	.Y(n_156));
   OAI21X4M g5272__6131 (.A0(FE_OFN114_n_154),
	.A1(FE_OFN75_n_153),
	.B0(FE_OFN185_n_107),
	.Y(n_155));
   OAI2BB1X2M g5251__1881 (.A0N(FE_OFN52_n_14),
	.A1N(n_358),
	.B0(FE_OFN68_n_54),
	.Y(n_152));
   NAND3BX2M g5280__5115 (.AN(FE_OFN31_u_uart_tx_tick_cnt_1),
	.B(n_160),
	.C(FE_OFN32_u_uart_tx_tick_cnt_0),
	.Y(n_150));
   OAI21X4M g5282__7482 (.A0(FE_OFN114_n_154),
	.A1(FE_OFN63_n_148),
	.B0(FE_OFN111_n_121),
	.Y(n_149));
   OAI21X4M g5285__4733 (.A0(FE_OFN114_n_154),
	.A1(n_146),
	.B0(n_115),
	.Y(n_147));
   AO22X2M g5287__6161 (.A0(n_160),
	.A1(n_61),
	.B0(n_95),
	.B1(FE_OFN30_u_uart_tx_tick_cnt_3),
	.Y(n_145));
   NOR2X2M g5289__9315 (.A(FE_OFN123_n_164),
	.B(FE_OFN10_u_uart_rx_bit_idx_1),
	.Y(n_144));
   AND2X2M g5273__9945 (.A(n_119),
	.B(n_14),
	.Y(n_189));
   OAI2BB1X2M g5309__2883 (.A0N(FE_OFN81_n_359),
	.A1N(n_139),
	.B0(FE_OFN20_u_uart_rx_data_reg_6),
	.Y(n_142));
   OAI2BB1X2M g5314__2346 (.A0N(FE_OFN8_u_uart_rx_state_0),
	.A1N(n_104),
	.B0(FE_OFN7_u_uart_rx_state_1),
	.Y(n_141));
   OAI2BB1X2M g5315__1666 (.A0N(n_106),
	.A1N(n_139),
	.B0(FE_OFN23_u_uart_rx_data_reg_3),
	.Y(n_140));
   SDFFRQX2M \u_uart_tx_data_reg_reg[4]  (.SI(u_uart_tx_data_reg[4]),
	.SE(FE_OFN89_n_157),
	.D(tx_data[4]),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_data_reg[4]));
   SDFFRQX2M \u_uart_tx_data_reg_reg[5]  (.SI(u_uart_tx_data_reg[5]),
	.SE(FE_OFN89_n_157),
	.D(tx_data[5]),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_data_reg[5]));
   SDFFRQX2M \u_uart_tx_data_reg_reg[2]  (.SI(u_uart_tx_data_reg[2]),
	.SE(FE_OFN89_n_157),
	.D(tx_data[2]),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_data_reg[2]));
   SDFFRQX2M \u_uart_tx_data_reg_reg[1]  (.SI(u_uart_tx_data_reg[1]),
	.SE(FE_OFN89_n_157),
	.D(tx_data[1]),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_data_reg[1]));
   SDFFRQX2M \u_uart_tx_data_reg_reg[7]  (.SI(u_uart_tx_data_reg[7]),
	.SE(FE_OFN89_n_157),
	.D(tx_data[7]),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_data_reg[7]));
   SDFFRQX2M \u_uart_tx_data_reg_reg[3]  (.SI(FE_OFN34_u_uart_tx_data_reg_3),
	.SE(FE_OFN89_n_157),
	.D(tx_data[3]),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_data_reg[3]));
   DFFRQX2M \u_baud_gen_count_reg[0]  (.D(n_92),
	.CK(clk),
	.RN(rst_n),
	.Q(u_baud_gen_count[0]));
   DFFRQX2M \u_baud_gen_count_reg[4]  (.D(n_90),
	.CK(clk),
	.RN(rst_n),
	.Q(u_baud_gen_count[4]));
   NAND3X2M g5277__7410 (.A(FE_OFN90_n_174),
	.B(n_44),
	.C(n_28),
	.Y(n_138));
   AO21X1M g5319__6417 (.A0(FE_OFN74_n_110),
	.A1(FE_OFN42_n_24),
	.B0(n_136),
	.Y(n_137));
   NOR2X4M g5291__5477 (.A(FE_OFN118_n_181),
	.B(FE_OFN50_u_uart_rx_rx_sync_ff2),
	.Y(n_135));
   OA21X2M g5196__2398 (.A0(FE_OFN1_u_baud_gen_count_5),
	.A1(FE_OFN72_n_89),
	.B0(n_133),
	.Y(n_134));
   NAND3X2M g5256__5107 (.A(n_174),
	.B(n_46),
	.C(n_44),
	.Y(n_132));
   NAND3X2M g5271__6260 (.A(n_86),
	.B(n_88),
	.C(FE_OFN53_n_18),
	.Y(n_130));
   NAND3X2M g5278__8428 (.A(FE_OFN90_n_174),
	.B(n_44),
	.C(n_124),
	.Y(n_125));
   NAND2X4M g5312__5526 (.A(FE_OFN107_n_103),
	.B(FE_OFN26_u_uart_rx_data_reg_0),
	.Y(n_123));
   SDFFRQX2M \u_uart_tx_data_reg_reg[6]  (.SI(FE_OFN173_u_uart_tx_data_reg_6),
	.SE(FE_OFN89_n_157),
	.D(tx_data[6]),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_data_reg[6]));
   SDFFRQX2M \u_uart_tx_data_reg_reg[0]  (.SI(FE_OFN157_u_uart_tx_data_reg_0),
	.SE(FE_OFN89_n_157),
	.D(tx_data[0]),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_data_reg[0]));
   NOR2X4M g5190__6783 (.A(n_133),
	.B(FE_OFN46_n_122),
	.Y(n_177));
   OAI2BB1X2M g5308__3680 (.A0N(n_52),
	.A1N(FE_OFN96_n_113),
	.B0(FE_OFN21_u_uart_rx_data_reg_5),
	.Y(n_121));
   OAI21X6M g5310__1617 (.A0(FE_OFN94_n_82),
	.A1(FE_OFN63_n_148),
	.B0(FE_OFN19_u_uart_rx_data_reg_7),
	.Y(n_120));
   AOI21X4M g5318__2802 (.A0(FE_OFN98_n_118),
	.A1(FE_OFN7_u_uart_rx_state_1),
	.B0(FE_OFN8_u_uart_rx_state_0),
	.Y(n_119));
   OAI2BB2X8M g5321__1705 (.A0N(FE_OFN66_n_49),
	.A1N(FE_OFN98_n_118),
	.B0(FE_OFN97_n_118),
	.B1(FE_OFN85_n_99),
	.Y(n_117));
   OAI2BB1X2M g5307__8246 (.A0N(FE_OFN81_n_359),
	.A1N(FE_OFN96_n_113),
	.B0(FE_OFN22_u_uart_rx_data_reg_4),
	.Y(n_115));
   CLKINVX4M g5324 (.A(FE_OFN118_n_181),
	.Y(n_166));
   CLKNAND2X2M g5296__7098 (.A(FE_OFN204_n_111),
	.B(FE_OFN74_n_110),
	.Y(n_112));
   NOR2X4M g5326__6131 (.A(FE_OFN86_n_108),
	.B(FE_OFN14_u_uart_rx_tick_cnt_1),
	.Y(n_109));
   OAI2BB1X2M g5293__1881 (.A0N(n_106),
	.A1N(FE_OFN96_n_113),
	.B0(FE_OFN25_u_uart_rx_data_reg_1),
	.Y(n_107));
   NAND2BX2M g5335__5115 (.AN(FE_OFN76_n_168),
	.B(n_139),
	.Y(n_105));
   NOR2X4M g5328__7482 (.A(FE_OFN86_n_108),
	.B(FE_OFN15_u_uart_rx_tick_cnt_0),
	.Y(n_158));
   NAND2X2M g5332__4733 (.A(n_104),
	.B(n_70),
	.Y(n_164));
   NAND2X2M g5342__6161 (.A(n_139),
	.B(FE_OFN50_u_uart_rx_rx_sync_ff2),
	.Y(n_179));
   NAND2BX1M g5336__9315 (.AN(FE_OFN76_n_168),
	.B(FE_OFN96_n_113),
	.Y(n_103));
   OR3X2M g5306__9945 (.A(FE_OFN98_n_118),
	.B(FE_OFN73_n_96),
	.C(FE_OFN7_u_uart_rx_state_1),
	.Y(n_102));
   OR2X2M g5327__2883 (.A(n_100),
	.B(FE_OFN85_n_99),
	.Y(n_101));
   CLKAND2X6M g5331__1666 (.A(FE_OFN84_n_94),
	.B(FE_OFN74_n_110),
	.Y(n_160));
   NAND2X2M g5330__7410 (.A(FE_OFN96_n_113),
	.B(FE_OFN50_u_uart_rx_rx_sync_ff2),
	.Y(n_154));
   DFFRQX2M u_baud_gen_baud_tick_16x_reg (.D(FE_OFN80_n_199),
	.CK(clk),
	.RN(rst_n),
	.Q(baud_tick_16x));
   OAI2BB1X4M g5323__6417 (.A0N(n_44),
	.A1N(n_84),
	.B0(FE_OFN74_n_110),
	.Y(n_174));
   OR2X2M g5333__5477 (.A(FE_OFN95_n_100),
	.B(n_77),
	.Y(n_181));
   NOR2X4M g5290__2398 (.A(n_97),
	.B(FE_OFN73_n_96),
	.Y(n_98));
   OAI2BB1X2M g5338__5107 (.A0N(FE_OFN74_n_110),
	.A1N(n_60),
	.B0(FE_OFN84_n_94),
	.Y(n_95));
   NOR2X3M g5266__6260 (.A(FE_OFN80_n_199),
	.B(FE_OFN205_n_59),
	.Y(n_93));
   NOR2X4M g5269__4319 (.A(FE_OFN80_n_199),
	.B(FE_OFN5_u_baud_gen_count_0),
	.Y(n_92));
   AOI2B1X4M g5224__5526 (.A0(n_75),
	.A1N(FE_OFN2_u_baud_gen_count_4),
	.B0(FE_OFN72_n_89),
	.Y(n_90));
   OAI2BB1X2M g5341__6783 (.A0N(n_23),
	.A1N(FE_OFN74_n_110),
	.B0(FE_OFN84_n_94),
	.Y(n_136));
   DFFRQX2M \u_baud_gen_count_reg[3]  (.D(n_76),
	.CK(clk),
	.RN(rst_n),
	.Q(u_baud_gen_count[3]));
   NAND2X4M g5203__3680 (.A(FE_OFN72_n_89),
	.B(FE_OFN1_u_baud_gen_count_5),
	.Y(n_133));
   NAND2BX2M g5337__1617 (.AN(n_65),
	.B(FE_OFN45_n_87),
	.Y(n_88));
   NAND2BX2M g5325__2802 (.AN(n_64),
	.B(FE_OFN28_u_uart_tx_bit_idx_1),
	.Y(n_86));
   INVXLM g5344 (.A(FE_OFN84_n_94),
	.Y(n_85));
   NAND3X2M g5339__1705 (.A(n_84),
	.B(FE_OFN61_n_83),
	.C(FE_OFN16_u_uart_tx_state_2),
	.Y(n_111));
   INVX4M g5345 (.A(FE_OFN94_n_82),
	.Y(n_139));
   INVXLM g5354 (.A(n_79),
	.Y(n_80));
   INVXLM g5363 (.A(n_157),
	.Y(n_78));
   XOR3X1M g5361__8246 (.A(tx_data[1]),
	.B(tx_data[6]),
	.C(FE_OFN162_n_31),
	.Y(n_127));
   INVX2M g5346 (.A(FE_OFN98_n_118),
	.Y(n_104));
   OAI2BB1X2M g5350__7098 (.A0N(n_77),
	.A1N(FE_OFN70_n_66),
	.B0(FE_OFN36_baud_tick_16x),
	.Y(n_108));
   OA21X2M g5311__6131 (.A0(FE_OFN3_u_baud_gen_count_3),
	.A1(FE_OFN58_n_58),
	.B0(n_75),
	.Y(n_76));
   AND3X4M g5340__5115 (.A(n_71),
	.B(n_72),
	.C(FE_OFN50_u_uart_rx_rx_sync_ff2),
	.Y(n_97));
   NAND3X2M g5352__7482 (.A(n_71),
	.B(n_70),
	.C(FE_OFN10_u_uart_rx_bit_idx_1),
	.Y(n_82));
   NAND2BX2M g5349__4733 (.AN(FE_OFN12_u_uart_rx_tick_cnt_3),
	.B(n_71),
	.Y(n_100));
   OAI2BB1X2M g5351__6161 (.A0N(FE_OFN36_baud_tick_16x),
	.A1N(n_69),
	.B0(FE_OFN74_n_110),
	.Y(n_94));
   AND3X2M g5305__9315 (.A(FE_OFN57_n_57),
	.B(FE_OFN55_n_33),
	.C(n_7),
	.Y(n_199));
   XNOR3X1M g5359__9945 (.A(FE_OFN20_u_uart_rx_data_reg_6),
	.B(FE_OFN25_u_uart_rx_data_reg_1),
	.C(n_16),
	.Y(n_68));
   OA22X4M g5358__2346 (.A0(FE_OFN70_n_66),
	.A1(FE_OFN36_baud_tick_16x),
	.B0(n_43),
	.B1(FE_OFN52_n_14),
	.Y(n_79));
   XOR3X1M g5357__1666 (.A(tx_data[0]),
	.B(tx_data[7]),
	.C(FE_OFN163_n_20),
	.Y(n_126));
   NOR2BX4M g5262__7410 (.AN(FE_OFN2_u_baud_gen_count_4),
	.B(n_75),
	.Y(n_89));
   AND3X2M g5362__6417 (.A(n_71),
	.B(n_70),
	.C(FE_OFN39_n_5),
	.Y(n_113));
   NAND2X2M g5353__5477 (.A(n_71),
	.B(FE_OFN12_u_uart_rx_tick_cnt_3),
	.Y(n_118));
   OR2X4M g5367__2398 (.A(n_3),
	.B(FE_OFN74_n_110),
	.Y(n_157));
   MX3X1M g5355__5107 (.S1(FE_OFN27_u_uart_tx_bit_idx_2),
	.S0(n_124),
	.C(n_30),
	.B(FE_OFN157_u_uart_tx_data_reg_0),
	.A(u_uart_tx_data_reg[1]),
	.Y(n_65));
   MX3X2M g5356__6260 (.S1(FE_OFN27_u_uart_tx_bit_idx_2),
	.S0(n_124),
	.C(n_29),
	.B(u_uart_tx_data_reg[2]),
	.A(FE_OFN34_u_uart_tx_data_reg_3),
	.Y(n_64));
   INVX2M g5343 (.A(FE_OFN69_n_63),
	.Y(n_84));
   INVX6M g5377 (.A(FE_OFN81_n_359),
	.Y(n_146));
   NAND2BX2M g5385__4319 (.AN(FE_OFN73_n_96),
	.B(FE_OFN7_u_uart_rx_state_1),
	.Y(n_99));
   NOR2X4M g5364__8428 (.A(n_60),
	.B(FE_OFN30_u_uart_tx_tick_cnt_3),
	.Y(n_61));
   AO21X2M g5372__5526 (.A0(n_34),
	.A1(FE_OFN44_n_32),
	.B0(FE_OFN58_n_58),
	.Y(n_59));
   NOR2BX2M g5347__6783 (.AN(u_baud_gen_count[2]),
	.B(n_39),
	.Y(n_57));
   OR2X2M g5365__3680 (.A(FE_OFN56_n_55),
	.B(FE_OFN50_u_uart_rx_rx_sync_ff2),
	.Y(n_56));
   NAND3BX2M g5348__1617 (.AN(n_60),
	.B(FE_OFN30_u_uart_tx_tick_cnt_3),
	.C(FE_OFN36_baud_tick_16x),
	.Y(n_63));
   DFFRQX2M \u_baud_gen_count_reg[1]  (.D(n_35),
	.CK(clk),
	.RN(rst_n),
	.Q(u_baud_gen_count[1]));
   NAND2X6M g5329__2802 (.A(FE_OFN58_n_58),
	.B(FE_OFN3_u_baud_gen_count_3),
	.Y(n_75));
   CLKINVX4M g5368 (.A(FE_OFN68_n_54),
	.Y(n_71));
   INVXLM g5378 (.A(FE_OFN63_n_148),
	.Y(n_52));
   NAND3X2M g5283__1705 (.A(n_44),
	.B(n_45),
	.C(FE_OFN27_u_uart_tx_bit_idx_2),
	.Y(n_50));
   INVX2M g5374 (.A(FE_OFN66_n_49),
	.Y(n_77));
   NAND2X2M g5395__8246 (.A(FE_OFN53_n_18),
	.B(n_40),
	.Y(n_110));
   AOI21BX2M g5369__7098 (.A0(FE_OFN13_u_uart_rx_tick_cnt_2),
	.A1(FE_OFN174_n_0),
	.B0N(n_21),
	.Y(n_47));
   CLKXOR2X2M g5334__6131 (.A(n_45),
	.B(FE_OFN27_u_uart_tx_bit_idx_2),
	.Y(n_46));
   NAND2BX2M g5373__1881 (.AN(n_19),
	.B(FE_OFN36_baud_tick_16x),
	.Y(n_54));
   NAND2X2M g5413__5115 (.A(n_14),
	.B(FE_OFN8_u_uart_rx_state_0),
	.Y(n_96));
   NOR2BX4M g5398__7482 (.AN(FE_OFN36_baud_tick_16x),
	.B(FE_OFN56_n_55),
	.Y(n_43));
   INVX1M g5376 (.A(FE_OFN154_n),
	.Y(n_106));
   NOR2X4M g5388__4733 (.A(FE_OFN56_n_55),
	.B(FE_OFN52_n_14),
	.Y(n_49));
   NAND2X2M g5389__6161 (.A(FE_OFN56_n_55),
	.B(FE_OFN52_n_14),
	.Y(n_66));
   NAND2X2M g5392__9315 (.A(n_37),
	.B(FE_OFN11_u_uart_rx_bit_idx_0),
	.Y(n_148));
   NOR2X4M g5397__9945 (.A(FE_OFN60_n_73),
	.B(n_40),
	.Y(n_41));
   OR3X2M g5370__2883 (.A(n_8),
	.B(FE_OFN1_u_baud_gen_count_5),
	.C(FE_OFN2_u_baud_gen_count_4),
	.Y(n_39));
   NOR2X4M g5383__2346 (.A(n_163),
	.B(FE_OFN9_u_uart_rx_bit_idx_2),
	.Y(n_36));
   NOR2BX4M g5384__1666 (.AN(n_34),
	.B(FE_OFN55_n_33),
	.Y(n_35));
   NAND2BX2M g5386__7410 (.AN(FE_OFN61_n_83),
	.B(FE_OFN16_u_uart_tx_state_2),
	.Y(n_69));
   AND2X6M g5393__6417 (.A(FE_OFN53_n_18),
	.B(FE_OFN17_u_uart_tx_state_1),
	.Y(n_44));
   NOR2X4M g5387__5477 (.A(n_34),
	.B(FE_OFN44_n_32),
	.Y(n_58));
   NAND2X2M g5390__2398 (.A(FE_OFN54_n_22),
	.B(FE_OFN11_u_uart_rx_bit_idx_0),
	.Y(n_153));
   AO22X2M g5402__6260 (.A0(n_124),
	.A1(u_uart_tx_data_reg[4]),
	.B0(FE_OFN29_u_uart_tx_bit_idx_0),
	.B1(u_uart_tx_data_reg[5]),
	.Y(n_30));
   AO22X2M g5400__4319 (.A0(n_124),
	.A1(FE_OFN173_u_uart_tx_data_reg_6),
	.B0(FE_OFN29_u_uart_tx_bit_idx_0),
	.B1(u_uart_tx_data_reg[7]),
	.Y(n_29));
   AO22X2M g5396__8428 (.A0(FE_OFN29_u_uart_tx_bit_idx_0),
	.A1(FE_OFN45_n_87),
	.B0(n_124),
	.B1(FE_OFN28_u_uart_tx_bit_idx_1),
	.Y(n_28));
   OR3X4M g5408__5526 (.A(FE_OFN43_n_25),
	.B(FE_OFN42_n_24),
	.C(n_23),
	.Y(n_60));
   AND3X4M g5407__6783 (.A(n_14),
	.B(n_12),
	.C(FE_OFN7_u_uart_rx_state_1),
	.Y(n_70));
   NAND2BX2M g5409__3680 (.AN(FE_OFN11_u_uart_rx_bit_idx_0),
	.B(FE_OFN54_n_22),
	.Y(n_168));
   DFFSQX2M u_uart_rx_rx_sync_ff2_reg (.D(u_uart_rx_rx_sync_ff1),
	.CK(clk),
	.SN(rst_n),
	.Q(u_uart_rx_rx_sync_ff2));
   NAND3BX4M g5399__1617 (.AN(FE_OFN13_u_uart_rx_tick_cnt_2),
	.B(FE_OFN15_u_uart_rx_tick_cnt_0),
	.C(FE_OFN14_u_uart_rx_tick_cnt_1),
	.Y(n_21));
   CLKXOR2X2M g5404__2802 (.A(tx_data[4]),
	.B(tx_data[2]),
	.Y(n_20));
   NAND3X2M g5401__1705 (.A(FE_OFN15_u_uart_rx_tick_cnt_0),
	.B(FE_OFN14_u_uart_rx_tick_cnt_1),
	.C(FE_OFN13_u_uart_rx_tick_cnt_2),
	.Y(n_19));
   CLKXOR2X2M g5405__5122 (.A(FE_OFN24_u_uart_rx_data_reg_2),
	.B(FE_OFN22_u_uart_rx_data_reg_4),
	.Y(n_17));
   CLKXOR2X2M g5406__8246 (.A(FE_OFN23_u_uart_rx_data_reg_3),
	.B(FE_OFN21_u_uart_rx_data_reg_5),
	.Y(n_16));
   INVXLM g5410 (.A(FE_OFN60_n_73),
	.Y(n_15));
   CLKAND2X4M g5424__7098 (.A(FE_OFN38_n_2),
	.B(FE_OFN9_u_uart_rx_bit_idx_2),
	.Y(n_37));
   NAND2X2M g5417__6131 (.A(n_72),
	.B(n_12),
	.Y(n_55));
   NOR2X4M g5428__1881 (.A(FE_OFN18_u_uart_tx_state_0),
	.B(FE_OFN16_u_uart_tx_state_2),
	.Y(n_18));
   CLKAND2X4M g5426__5115 (.A(FE_OFN29_u_uart_tx_bit_idx_0),
	.B(FE_OFN28_u_uart_tx_bit_idx_1),
	.Y(n_45));
   NOR2X4M g5423__7482 (.A(FE_OFN9_u_uart_rx_bit_idx_2),
	.B(FE_OFN12_u_uart_rx_tick_cnt_3),
	.Y(n_22));
   NAND2X4M g5427__4733 (.A(FE_OFN5_u_baud_gen_count_0),
	.B(FE_OFN4_u_baud_gen_count_1),
	.Y(n_34));
   NOR2X4M g5414__6161 (.A(FE_OFN17_u_uart_tx_state_1),
	.B(FE_OFN18_u_uart_tx_state_0),
	.Y(n_83));
   NAND2X1M g5422__9315 (.A(u_baud_gen_count[6]),
	.B(FE_OFN188_u_baud_gen_count_8),
	.Y(n_8));
   NOR2X4M g5411__9945 (.A(FE_OFN3_u_baud_gen_count_3),
	.B(FE_OFN0_u_baud_gen_count_7),
	.Y(n_7));
   DFFSQX1M u_uart_rx_rx_sync_ff1_reg (.D(rx_serial),
	.CK(clk),
	.SN(rst_n),
	.Q(u_uart_rx_rx_sync_ff1));
   NOR2X4M g5425__2883 (.A(FE_OFN4_u_baud_gen_count_1),
	.B(FE_OFN5_u_baud_gen_count_0),
	.Y(n_33));
   NAND2X4M g5415__2346 (.A(FE_OFN11_u_uart_rx_bit_idx_0),
	.B(FE_OFN10_u_uart_rx_bit_idx_1),
	.Y(n_163));
   NAND2BX2M g5416__1666 (.AN(FE_OFN16_u_uart_tx_state_2),
	.B(FE_OFN18_u_uart_tx_state_0),
	.Y(n_73));
   CLKINVX2M g5438 (.A(tx_start),
	.Y(n_3));
   CLKINVX2M g5440 (.A(FE_OFN8_u_uart_rx_state_0),
	.Y(n_12));
   INVX4M g5443 (.A(FE_OFN17_u_uart_tx_state_1),
	.Y(n_40));
   INVX4M g5448 (.A(FE_OFN7_u_uart_rx_state_1),
	.Y(n_72));
   INVX4M g5453 (.A(FE_OFN6_u_uart_rx_state_2),
	.Y(n_14));
   INVX8M g5437 (.A(FE_OFN29_u_uart_tx_bit_idx_0),
	.Y(n_124));
   INVX2M drc_bufs5579 (.A(FE_OFN32_u_uart_tx_tick_cnt_0),
	.Y(n_23));
   CLKINVX4M drc_bufs5606 (.A(FE_OFN41_n_9),
	.Y(n_10));
   DFFRX2M \u_uart_rx_bit_idx_reg[2]  (.D(n_361),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_bit_idx[2]),
	.QN(n_6));
   DFFRX1M \u_uart_rx_bit_idx_reg[1]  (.D(FE_OFN131_n_208),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_bit_idx[1]),
	.QN(n_5));
   DFFRX2M \u_uart_rx_tick_cnt_reg[3]  (.D(n_213),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_tick_cnt[3]),
	.QN(n_2));
   DFFRX1M \u_uart_tx_tick_cnt_reg[1]  (.D(n_186),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_tick_cnt[1]),
	.QN(n_24));
   DFFRX1M \u_uart_tx_bit_idx_reg[1]  (.D(FE_OFN196_n_176),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_bit_idx[1]),
	.QN(n_87));
   DFFRX1M \u_uart_tx_bit_idx_reg[2]  (.D(FE_OFN164_n_170),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_bit_idx[2]),
	.QN(n_1));
   DFFRX1M \u_uart_rx_tick_cnt_reg[1]  (.D(n_194),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_tick_cnt[1]),
	.QN(n_0));
   DFFRX1M \u_baud_gen_count_reg[2]  (.D(n_93),
	.CK(clk),
	.RN(rst_n),
	.Q(u_baud_gen_count[2]),
	.QN(n_32));
   DFFRX1M \u_baud_gen_count_reg[6]  (.D(FE_OFN161_n_200),
	.CK(clk),
	.RN(rst_n),
	.Q(u_baud_gen_count[6]),
	.QN(n_122));
   DFFRX1M \u_uart_tx_tick_cnt_reg[2]  (.D(n_184),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_tx_tick_cnt[2]),
	.QN(n_25));
   DFFRX2M \u_uart_rx_bit_idx_reg[0]  (.D(FE_OFN182_n_201),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_bit_idx[0]),
	.QN(n_9));
   DFFRX1M \u_uart_rx_data_reg_reg[7]  (.D(n_180),
	.CK(clk),
	.RN(rst_n),
	.Q(u_uart_rx_data_reg[7]),
	.QN(n_337));
   OR2X1M g2 (.A(n_205),
	.B(FE_OFN61_n_83),
	.Y(n_357));
   OR2X2M g5642 (.A(n_97),
	.B(n_66),
	.Y(n_358));
   NOR2BX4M g5643 (.AN(n_37),
	.B(n_10),
	.Y(n_359));
   XNOR3X2M g5644 (.A(FE_OFN48_n_337),
	.B(FE_OFN26_u_uart_rx_data_reg_0),
	.C(n_17),
	.Y(n_360));
   AO2B2X2M g5645 (.A0(n_36),
	.A1N(FE_OFN123_n_164),
	.B0(n_185),
	.B1(FE_OFN9_u_uart_rx_bit_idx_2),
	.Y(n_361));
   XOR3X1M g5646 (.A(FE_OFN64_n_360),
	.B(FE_OFN59_n_68),
	.C(FE_OFN49_u_uart_rx_parity_calc),
	.Y(n_362));
   AO21X2M g5647 (.A0(FE_OFN67_n_50),
	.A1(n_73),
	.B0(FE_OFN69_n_63),
	.Y(n_363));
   OAI21BX4M g5650 (.A0(FE_OFN60_n_73),
	.A1(FE_OFN17_u_uart_tx_state_1),
	.B0N(n_44),
	.Y(n_369));
endmodule

