###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ece.nitw.ac.in)
#  Generated on:      Mon Jun 29 17:34:29 2026
#  Design:            uart_top
###############################################################
current_design uart_top
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 20.000000 -waveform {0.000000 10.000000}
set_clock_transition  -rise -min 0.15 [get_clocks {clk}]
set_clock_transition  -rise -max 0.15 [get_clocks {clk}]
set_clock_transition  -fall -min 0.15 [get_clocks {clk}]
set_clock_transition  -fall -max 0.15 [get_clocks {clk}]
set_propagated_clock  [get_ports {clk}]
set_wire_load_mode enclosed
set_max_fanout 16  [get_designs {uart_top}]
set_max_transition 0.3  [get_designs {uart_top}]
set_input_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_data[2]}]
set_input_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_data[2]}]
set_input_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_data[0]}]
set_input_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_data[0]}]
set_input_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_start}]
set_input_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_start}]
set_input_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_data[7]}]
set_input_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_data[7]}]
set_input_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_data[5]}]
set_input_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_data[5]}]
set_input_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_data[3]}]
set_input_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_data[3]}]
set_input_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_data[1]}]
set_input_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_data[1]}]
set_input_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_data[6]}]
set_input_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_data[6]}]
set_input_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_data[4]}]
set_input_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_data[4]}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {rx_data[6]}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {rx_data[6]}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {rx_data[4]}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {rx_data[4]}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {rx_data[2]}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {rx_data[2]}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {rx_data[0]}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {rx_data[0]}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_busy}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_busy}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {parity_error}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {parity_error}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {rx_data[7]}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {rx_data[7]}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {tx_serial}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {tx_serial}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {rx_data[5]}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {rx_data[5]}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {rx_data[3]}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {rx_data[3]}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {rx_data[1]}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {rx_data[1]}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {rx_done}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {rx_done}]
set_output_delay -add_delay 1 -min -clock [get_clocks {clk}] [get_ports {framing_error}]
set_output_delay -add_delay 8 -max -clock [get_clocks {clk}] [get_ports {framing_error}]
set_clock_uncertainty 0.08 -hold [get_clocks {clk}]
set_clock_uncertainty 0.15 -setup [get_clocks {clk}]
set_false_path  -from [get_ports {rst_n rx_serial}] 
set_clock_latency -source -early -max -rise  -0.00314444 [get_ports {clk}] -clock clk 
set_clock_latency -source -early -max -fall  -0.00315675 [get_ports {clk}] -clock clk 
set_clock_latency -source -late -max -rise  -0.00314444 [get_ports {clk}] -clock clk 
set_clock_latency -source -late -max -fall  -0.00315675 [get_ports {clk}] -clock clk 
